--
-- PostgreSQL database dump
--

\restrict 1z9fbfo1Ymf1sTOgNL2odt8fmdGxNJZRfNWSLh4pL1qNKnjJiaEcKZmUOPE1gQ5

-- Dumped from database version 18.0
-- Dumped by pg_dump version 18.0

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: app_activitylog; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.app_activitylog (
    id bigint NOT NULL,
    action character varying(50) NOT NULL,
    model_name character varying(100) NOT NULL,
    object_repr text NOT NULL,
    description text,
    "timestamp" timestamp with time zone NOT NULL,
    user_id integer
);


--
-- Name: app_activitylog_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.app_activitylog ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_activitylog_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: app_adminpermission; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.app_adminpermission (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    codename character varying(100) NOT NULL,
    description text NOT NULL
);


--
-- Name: app_adminpermission_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.app_adminpermission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_adminpermission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: app_badstockreport; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.app_badstockreport (
    id bigint NOT NULL,
    quantity_removed integer NOT NULL,
    remarks text NOT NULL,
    reported_at timestamp with time zone NOT NULL,
    reported_by_id integer,
    supply_id bigint NOT NULL,
    CONSTRAINT app_badstockreport_quantity_removed_check CHECK ((quantity_removed >= 0))
);


--
-- Name: app_badstockreport_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.app_badstockreport ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_badstockreport_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: app_borrowrequest; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.app_borrowrequest (
    id bigint NOT NULL,
    quantity integer NOT NULL,
    status character varying(20) NOT NULL,
    borrow_date timestamp with time zone NOT NULL,
    return_date date NOT NULL,
    actual_return_date date,
    purpose text NOT NULL,
    user_id integer NOT NULL,
    property_id bigint NOT NULL,
    remarks text,
    CONSTRAINT app_borrowrequest_quantity_check CHECK ((quantity >= 0))
);


--
-- Name: app_borrowrequest_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.app_borrowrequest ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_borrowrequest_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: app_borrowrequestbatch; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.app_borrowrequestbatch (
    id bigint NOT NULL,
    request_date timestamp with time zone NOT NULL,
    purpose text NOT NULL,
    status character varying(20) NOT NULL,
    approved_date timestamp with time zone,
    claimed_date timestamp with time zone,
    returned_date timestamp with time zone,
    completed_date timestamp with time zone,
    remarks text,
    claimed_by_id integer,
    user_id integer NOT NULL,
    voided_by_id integer,
    voided_date timestamp with time zone,
    approved_by_id integer
);


--
-- Name: app_borrowrequestbatch_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.app_borrowrequestbatch ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_borrowrequestbatch_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: app_borrowrequestitem; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.app_borrowrequestitem (
    id bigint NOT NULL,
    quantity integer NOT NULL,
    approved_quantity integer,
    return_date date NOT NULL,
    actual_return_date date,
    status character varying(20) NOT NULL,
    approved boolean NOT NULL,
    claimed_date timestamp with time zone,
    remarks text,
    batch_request_id bigint NOT NULL,
    property_id bigint NOT NULL,
    near_overdue_notified boolean NOT NULL,
    overdue_notified boolean NOT NULL,
    from_reservation boolean NOT NULL,
    CONSTRAINT app_borrowrequestitem_approved_quantity_check CHECK ((approved_quantity >= 0)),
    CONSTRAINT app_borrowrequestitem_quantity_check CHECK ((quantity >= 0))
);


--
-- Name: app_borrowrequestitem_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.app_borrowrequestitem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_borrowrequestitem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: app_damagereport; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.app_damagereport (
    id bigint NOT NULL,
    description text NOT NULL,
    status character varying(20) NOT NULL,
    report_date timestamp with time zone NOT NULL,
    user_id integer NOT NULL,
    item_id bigint NOT NULL,
    remarks text,
    deleted_at timestamp with time zone,
    deleted_by_id integer,
    image_size integer,
    image_data bytea,
    image_name character varying(255),
    image_type character varying(50) NOT NULL,
    CONSTRAINT app_damagereport_image_size_check CHECK ((image_size >= 0))
);


--
-- Name: app_damagereport_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.app_damagereport ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_damagereport_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: app_department; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.app_department (
    id bigint NOT NULL,
    name character varying(100) NOT NULL
);


--
-- Name: app_department_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.app_department ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_department_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: app_lostitem; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.app_lostitem (
    id bigint NOT NULL,
    description text NOT NULL,
    last_seen_location character varying(255),
    last_seen_date date,
    status character varying(20) NOT NULL,
    remarks text,
    report_date timestamp with time zone NOT NULL,
    item_id bigint NOT NULL,
    user_id integer NOT NULL
);


--
-- Name: app_lostitem_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.app_lostitem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_lostitem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: app_notification; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.app_notification (
    id bigint NOT NULL,
    message text NOT NULL,
    is_read boolean NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    user_id integer NOT NULL,
    remarks text
);


--
-- Name: app_notification_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.app_notification ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_notification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: app_ppmp; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.app_ppmp (
    id bigint NOT NULL,
    year integer NOT NULL,
    file character varying(100) NOT NULL,
    upload_date timestamp with time zone NOT NULL,
    department_id bigint NOT NULL,
    uploaded_by_id integer,
    CONSTRAINT app_ppmp_year_check CHECK ((year >= 0))
);


--
-- Name: app_ppmp_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.app_ppmp ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_ppmp_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: app_ppmpitem; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.app_ppmpitem (
    id bigint NOT NULL,
    unit text,
    mode text,
    supplies_materials_expense text,
    office_supplies_expense text,
    common_office_supplies text,
    description text NOT NULL,
    unit_measure text,
    unit_price numeric(10,2),
    quantity integer NOT NULL,
    total_amount numeric(12,2),
    row_number integer NOT NULL,
    ppmp_id bigint NOT NULL,
    released integer NOT NULL,
    CONSTRAINT app_ppmpitem_quantity_check CHECK ((quantity >= 0)),
    CONSTRAINT app_ppmpitem_released_check CHECK ((released >= 0)),
    CONSTRAINT app_ppmpitem_row_number_check CHECK ((row_number >= 0))
);


--
-- Name: app_ppmpitem_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.app_ppmpitem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_ppmpitem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: app_ppmpitemrelease; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.app_ppmpitemrelease (
    id bigint NOT NULL,
    quantity_released integer NOT NULL,
    release_date timestamp with time zone NOT NULL,
    remarks text,
    ppmp_item_id bigint NOT NULL,
    released_by_id integer,
    supply_request_id bigint,
    supply_request_item_id bigint,
    CONSTRAINT app_ppmpitemrelease_quantity_released_check CHECK ((quantity_released >= 0))
);


--
-- Name: app_ppmpitemrelease_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.app_ppmpitemrelease ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_ppmpitemrelease_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: app_property; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.app_property (
    id bigint NOT NULL,
    property_name character varying(100) NOT NULL,
    quantity integer NOT NULL,
    barcode character varying(100),
    condition character varying(100) NOT NULL,
    category_id bigint,
    description text,
    location character varying(255),
    unit_of_measure character varying(50),
    unit_value numeric(10,2),
    availability character varying(20) NOT NULL,
    overall_quantity integer NOT NULL,
    property_number character varying(100),
    is_archived boolean NOT NULL,
    accountable_person character varying(255),
    year_acquired date,
    old_property_number character varying(100),
    quantity_per_physical_count integer NOT NULL,
    barcode_image character varying(100),
    reserved_quantity integer NOT NULL,
    serial_number character varying(100),
    ppmp_references jsonb,
    remarks text,
    CONSTRAINT app_property_overall_quantity_check CHECK ((overall_quantity >= 0)),
    CONSTRAINT app_property_quantity_check CHECK ((quantity >= 0)),
    CONSTRAINT app_property_quantity_per_physical_count_check CHECK ((quantity_per_physical_count >= 0)),
    CONSTRAINT app_property_reserved_quantity_check CHECK ((reserved_quantity >= 0))
);


--
-- Name: app_property_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.app_property ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_property_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: app_propertycategory; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.app_propertycategory (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    uacs bigint
);


--
-- Name: app_propertycategory_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.app_propertycategory ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_propertycategory_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: app_propertyhistory; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.app_propertyhistory (
    id bigint NOT NULL,
    action character varying(50) NOT NULL,
    field_name character varying(100) NOT NULL,
    old_value text,
    new_value text,
    "timestamp" timestamp with time zone NOT NULL,
    property_id bigint NOT NULL,
    user_id integer,
    remarks text
);


--
-- Name: app_propertyhistory_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.app_propertyhistory ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_propertyhistory_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: app_propertyppmpallocation; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.app_propertyppmpallocation (
    id bigint NOT NULL,
    quantity_allocated integer NOT NULL,
    allocated_date timestamp with time zone NOT NULL,
    allocated_by_id integer,
    ppmp_item_id bigint NOT NULL,
    property_id bigint NOT NULL,
    CONSTRAINT app_propertyppmpallocation_quantity_allocated_check CHECK ((quantity_allocated >= 0))
);


--
-- Name: app_propertyppmpallocation_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.app_propertyppmpallocation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_propertyppmpallocation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: app_reservation; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.app_reservation (
    id bigint NOT NULL,
    quantity integer NOT NULL,
    reservation_date timestamp with time zone NOT NULL,
    return_date date NOT NULL,
    approved_date timestamp with time zone,
    purpose text NOT NULL,
    item_id bigint NOT NULL,
    user_id integer NOT NULL,
    needed_date date,
    status character varying(20) NOT NULL,
    remarks text,
    generated_borrow_batch_id bigint,
    batch_id character varying(100),
    batch_request_date timestamp with time zone,
    CONSTRAINT app_reservation_quantity_check CHECK ((quantity >= 0))
);


--
-- Name: app_reservation_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.app_reservation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_reservation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: app_reservationbatch; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.app_reservationbatch (
    id bigint NOT NULL,
    request_date timestamp with time zone NOT NULL,
    purpose text NOT NULL,
    status character varying(20) NOT NULL,
    approved_date timestamp with time zone,
    remarks text,
    generated_borrow_batch_id bigint,
    user_id integer NOT NULL,
    voided_by_id integer,
    voided_date timestamp with time zone
);


--
-- Name: app_reservationbatch_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.app_reservationbatch ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_reservationbatch_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: app_reservationitem; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.app_reservationitem (
    id bigint NOT NULL,
    quantity integer NOT NULL,
    needed_date date,
    return_date date NOT NULL,
    status character varying(20) NOT NULL,
    approved boolean NOT NULL,
    remarks text,
    batch_request_id bigint NOT NULL,
    property_id bigint NOT NULL,
    CONSTRAINT app_reservationitem_quantity_check CHECK ((quantity >= 0))
);


--
-- Name: app_reservationitem_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.app_reservationitem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_reservationitem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: app_supply; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.app_supply (
    id bigint NOT NULL,
    supply_name character varying(255) NOT NULL,
    date_received date NOT NULL,
    barcode character varying(100),
    category_id bigint,
    available_for_request boolean NOT NULL,
    last_updated timestamp with time zone NOT NULL,
    description text,
    subcategory_id bigint,
    expiration_date date,
    is_archived boolean NOT NULL,
    barcode_image character varying(100),
    unit character varying(50)
);


--
-- Name: app_supply_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.app_supply ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_supply_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: app_supplycategory; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.app_supplycategory (
    id bigint NOT NULL,
    name character varying(100) NOT NULL
);


--
-- Name: app_supplycategory_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.app_supplycategory ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_supplycategory_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: app_supplyhistory; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.app_supplyhistory (
    id bigint NOT NULL,
    action character varying(50) NOT NULL,
    field_name character varying(100) NOT NULL,
    old_value text,
    new_value text,
    "timestamp" timestamp with time zone NOT NULL,
    supply_id bigint NOT NULL,
    user_id integer,
    remarks text
);


--
-- Name: app_supplyhistory_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.app_supplyhistory ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_supplyhistory_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: app_supplyquantity; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.app_supplyquantity (
    id bigint NOT NULL,
    current_quantity integer NOT NULL,
    minimum_threshold integer NOT NULL,
    last_updated timestamp with time zone NOT NULL,
    supply_id bigint NOT NULL,
    reserved_quantity integer NOT NULL,
    CONSTRAINT app_supplyquantity_current_quantity_check CHECK ((current_quantity >= 0)),
    CONSTRAINT app_supplyquantity_minimum_threshold_check CHECK ((minimum_threshold >= 0)),
    CONSTRAINT app_supplyquantity_reserved_quantity_check CHECK ((reserved_quantity >= 0))
);


--
-- Name: app_supplyquantity_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.app_supplyquantity ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_supplyquantity_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: app_supplyrequest; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.app_supplyrequest (
    id bigint NOT NULL,
    quantity integer NOT NULL,
    request_date timestamp with time zone NOT NULL,
    purpose text NOT NULL,
    approved_date timestamp with time zone,
    status character varying(20) NOT NULL,
    supply_id bigint NOT NULL,
    user_id integer NOT NULL,
    remarks text,
    CONSTRAINT app_supplyrequest_quantity_check CHECK ((quantity >= 0))
);


--
-- Name: app_supplyrequest_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.app_supplyrequest ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_supplyrequest_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: app_supplyrequestbatch; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.app_supplyrequestbatch (
    id bigint NOT NULL,
    request_date timestamp with time zone NOT NULL,
    purpose text NOT NULL,
    status character varying(20) NOT NULL,
    approved_date timestamp with time zone,
    remarks text,
    user_id integer NOT NULL,
    claimed_date timestamp with time zone,
    completed_date timestamp with time zone,
    claimed_by_id integer,
    approved_by_id integer,
    voided_by_id integer,
    voided_date timestamp with time zone
);


--
-- Name: app_supplyrequestbatch_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.app_supplyrequestbatch ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_supplyrequestbatch_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: app_supplyrequestitem; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.app_supplyrequestitem (
    id bigint NOT NULL,
    quantity integer NOT NULL,
    approved boolean NOT NULL,
    remarks text,
    batch_request_id bigint NOT NULL,
    supply_id bigint NOT NULL,
    status character varying(20) NOT NULL,
    approved_quantity integer,
    claimed_date timestamp with time zone,
    ppmp_item_id bigint,
    ppmp_year integer,
    ppmp_allocations jsonb,
    CONSTRAINT app_supplyrequestitem_approved_quantity_check CHECK ((approved_quantity >= 0)),
    CONSTRAINT app_supplyrequestitem_ppmp_year_check CHECK ((ppmp_year >= 0)),
    CONSTRAINT app_supplyrequestitem_quantity_check CHECK ((quantity >= 0))
);


--
-- Name: app_supplyrequestitem_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.app_supplyrequestitem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_supplyrequestitem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: app_supplysubcategory; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.app_supplysubcategory (
    id bigint NOT NULL,
    name character varying(100) NOT NULL
);


--
-- Name: app_supplysubcategory_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.app_supplysubcategory ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_supplysubcategory_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: app_userprofile; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.app_userprofile (
    id bigint NOT NULL,
    role character varying(20) NOT NULL,
    department_id bigint,
    phone character varying(20),
    user_id integer NOT NULL,
    designation character varying(100),
    auto_enable_at timestamp with time zone,
    must_change_password boolean NOT NULL,
    has_limited_access boolean NOT NULL
);


--
-- Name: app_userprofile_admin_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.app_userprofile_admin_permissions (
    id bigint NOT NULL,
    userprofile_id bigint NOT NULL,
    adminpermission_id bigint NOT NULL
);


--
-- Name: app_userprofile_admin_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.app_userprofile_admin_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_userprofile_admin_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: app_userprofile_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.app_userprofile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_userprofile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: app_usersession; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.app_usersession (
    id bigint NOT NULL,
    session_key character varying(40) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    last_activity timestamp with time zone NOT NULL,
    ip_address character varying(100),
    user_agent text,
    user_id integer NOT NULL
);


--
-- Name: app_usersession_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.app_usersession ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_usersession_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_apscheduler_djangojob; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_apscheduler_djangojob (
    id character varying(255) NOT NULL,
    next_run_time timestamp with time zone,
    job_state bytea NOT NULL
);


--
-- Name: django_apscheduler_djangojobexecution; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_apscheduler_djangojobexecution (
    id bigint NOT NULL,
    status character varying(50) NOT NULL,
    run_time timestamp with time zone NOT NULL,
    duration numeric(15,2),
    finished numeric(15,2),
    exception character varying(1000),
    traceback text,
    job_id character varying(255) NOT NULL
);


--
-- Name: django_apscheduler_djangojobexecution_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_apscheduler_djangojobexecution ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_apscheduler_djangojobexecution_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


--
-- Name: app_activitylog app_activitylog_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_activitylog
    ADD CONSTRAINT app_activitylog_pkey PRIMARY KEY (id);


--
-- Name: app_adminpermission app_adminpermission_codename_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_adminpermission
    ADD CONSTRAINT app_adminpermission_codename_key UNIQUE (codename);


--
-- Name: app_adminpermission app_adminpermission_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_adminpermission
    ADD CONSTRAINT app_adminpermission_name_key UNIQUE (name);


--
-- Name: app_adminpermission app_adminpermission_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_adminpermission
    ADD CONSTRAINT app_adminpermission_pkey PRIMARY KEY (id);


--
-- Name: app_badstockreport app_badstockreport_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_badstockreport
    ADD CONSTRAINT app_badstockreport_pkey PRIMARY KEY (id);


--
-- Name: app_borrowrequest app_borrowrequest_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_borrowrequest
    ADD CONSTRAINT app_borrowrequest_pkey PRIMARY KEY (id);


--
-- Name: app_borrowrequestbatch app_borrowrequestbatch_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_borrowrequestbatch
    ADD CONSTRAINT app_borrowrequestbatch_pkey PRIMARY KEY (id);


--
-- Name: app_borrowrequestitem app_borrowrequestitem_batch_request_id_propert_48dd372d_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_borrowrequestitem
    ADD CONSTRAINT app_borrowrequestitem_batch_request_id_propert_48dd372d_uniq UNIQUE (batch_request_id, property_id);


--
-- Name: app_borrowrequestitem app_borrowrequestitem_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_borrowrequestitem
    ADD CONSTRAINT app_borrowrequestitem_pkey PRIMARY KEY (id);


--
-- Name: app_damagereport app_damagereport_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_damagereport
    ADD CONSTRAINT app_damagereport_pkey PRIMARY KEY (id);


--
-- Name: app_department app_department_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_department
    ADD CONSTRAINT app_department_name_key UNIQUE (name);


--
-- Name: app_department app_department_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_department
    ADD CONSTRAINT app_department_pkey PRIMARY KEY (id);


--
-- Name: app_lostitem app_lostitem_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_lostitem
    ADD CONSTRAINT app_lostitem_pkey PRIMARY KEY (id);


--
-- Name: app_notification app_notification_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_notification
    ADD CONSTRAINT app_notification_pkey PRIMARY KEY (id);


--
-- Name: app_ppmp app_ppmp_department_id_year_112e4807_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_ppmp
    ADD CONSTRAINT app_ppmp_department_id_year_112e4807_uniq UNIQUE (department_id, year);


--
-- Name: app_ppmp app_ppmp_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_ppmp
    ADD CONSTRAINT app_ppmp_pkey PRIMARY KEY (id);


--
-- Name: app_ppmpitem app_ppmpitem_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_ppmpitem
    ADD CONSTRAINT app_ppmpitem_pkey PRIMARY KEY (id);


--
-- Name: app_ppmpitemrelease app_ppmpitemrelease_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_ppmpitemrelease
    ADD CONSTRAINT app_ppmpitemrelease_pkey PRIMARY KEY (id);


--
-- Name: app_property app_property_barcode_431a43d6_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_property
    ADD CONSTRAINT app_property_barcode_431a43d6_uniq UNIQUE (barcode);


--
-- Name: app_property app_property_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_property
    ADD CONSTRAINT app_property_pkey PRIMARY KEY (id);


--
-- Name: app_property app_property_property_number_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_property
    ADD CONSTRAINT app_property_property_number_key UNIQUE (property_number);


--
-- Name: app_propertycategory app_propertycategory_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_propertycategory
    ADD CONSTRAINT app_propertycategory_name_key UNIQUE (name);


--
-- Name: app_propertycategory app_propertycategory_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_propertycategory
    ADD CONSTRAINT app_propertycategory_pkey PRIMARY KEY (id);


--
-- Name: app_propertyhistory app_propertyhistory_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_propertyhistory
    ADD CONSTRAINT app_propertyhistory_pkey PRIMARY KEY (id);


--
-- Name: app_propertyppmpallocation app_propertyppmpallocation_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_propertyppmpallocation
    ADD CONSTRAINT app_propertyppmpallocation_pkey PRIMARY KEY (id);


--
-- Name: app_reservation app_reservation_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_reservation
    ADD CONSTRAINT app_reservation_pkey PRIMARY KEY (id);


--
-- Name: app_reservationbatch app_reservationbatch_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_reservationbatch
    ADD CONSTRAINT app_reservationbatch_pkey PRIMARY KEY (id);


--
-- Name: app_reservationitem app_reservationitem_batch_request_id_property_id_d51a6404_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_reservationitem
    ADD CONSTRAINT app_reservationitem_batch_request_id_property_id_d51a6404_uniq UNIQUE (batch_request_id, property_id);


--
-- Name: app_reservationitem app_reservationitem_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_reservationitem
    ADD CONSTRAINT app_reservationitem_pkey PRIMARY KEY (id);


--
-- Name: app_supply app_supply_barcode_eedeb821_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_supply
    ADD CONSTRAINT app_supply_barcode_eedeb821_uniq UNIQUE (barcode);


--
-- Name: app_supply app_supply_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_supply
    ADD CONSTRAINT app_supply_pkey PRIMARY KEY (id);


--
-- Name: app_supplycategory app_supplycategory_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_supplycategory
    ADD CONSTRAINT app_supplycategory_name_key UNIQUE (name);


--
-- Name: app_supplycategory app_supplycategory_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_supplycategory
    ADD CONSTRAINT app_supplycategory_pkey PRIMARY KEY (id);


--
-- Name: app_supplyhistory app_supplyhistory_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_supplyhistory
    ADD CONSTRAINT app_supplyhistory_pkey PRIMARY KEY (id);


--
-- Name: app_supplyquantity app_supplyquantity_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_supplyquantity
    ADD CONSTRAINT app_supplyquantity_pkey PRIMARY KEY (id);


--
-- Name: app_supplyquantity app_supplyquantity_supply_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_supplyquantity
    ADD CONSTRAINT app_supplyquantity_supply_id_key UNIQUE (supply_id);


--
-- Name: app_supplyrequest app_supplyrequest_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_supplyrequest
    ADD CONSTRAINT app_supplyrequest_pkey PRIMARY KEY (id);


--
-- Name: app_supplyrequestbatch app_supplyrequestbatch_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_supplyrequestbatch
    ADD CONSTRAINT app_supplyrequestbatch_pkey PRIMARY KEY (id);


--
-- Name: app_supplyrequestitem app_supplyrequestitem_batch_request_id_supply_id_5e677cd1_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_supplyrequestitem
    ADD CONSTRAINT app_supplyrequestitem_batch_request_id_supply_id_5e677cd1_uniq UNIQUE (batch_request_id, supply_id);


--
-- Name: app_supplyrequestitem app_supplyrequestitem_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_supplyrequestitem
    ADD CONSTRAINT app_supplyrequestitem_pkey PRIMARY KEY (id);


--
-- Name: app_supplysubcategory app_supplysubcategory_name_61dc2d7b_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_supplysubcategory
    ADD CONSTRAINT app_supplysubcategory_name_61dc2d7b_uniq UNIQUE (name);


--
-- Name: app_supplysubcategory app_supplysubcategory_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_supplysubcategory
    ADD CONSTRAINT app_supplysubcategory_pkey PRIMARY KEY (id);


--
-- Name: app_userprofile_admin_permissions app_userprofile_admin_pe_userprofile_id_adminperm_7be107f5_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_userprofile_admin_permissions
    ADD CONSTRAINT app_userprofile_admin_pe_userprofile_id_adminperm_7be107f5_uniq UNIQUE (userprofile_id, adminpermission_id);


--
-- Name: app_userprofile_admin_permissions app_userprofile_admin_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_userprofile_admin_permissions
    ADD CONSTRAINT app_userprofile_admin_permissions_pkey PRIMARY KEY (id);


--
-- Name: app_userprofile app_userprofile_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_userprofile
    ADD CONSTRAINT app_userprofile_pkey PRIMARY KEY (id);


--
-- Name: app_userprofile app_userprofile_user_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_userprofile
    ADD CONSTRAINT app_userprofile_user_id_key UNIQUE (user_id);


--
-- Name: app_usersession app_usersession_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_usersession
    ADD CONSTRAINT app_usersession_pkey PRIMARY KEY (id);


--
-- Name: app_usersession app_usersession_session_key_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_usersession
    ADD CONSTRAINT app_usersession_session_key_key UNIQUE (session_key);


--
-- Name: app_usersession app_usersession_user_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_usersession
    ADD CONSTRAINT app_usersession_user_id_key UNIQUE (user_id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_apscheduler_djangojob django_apscheduler_djangojob_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_apscheduler_djangojob
    ADD CONSTRAINT django_apscheduler_djangojob_pkey PRIMARY KEY (id);


--
-- Name: django_apscheduler_djangojobexecution django_apscheduler_djangojobexecution_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_apscheduler_djangojobexecution
    ADD CONSTRAINT django_apscheduler_djangojobexecution_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: django_apscheduler_djangojobexecution unique_job_executions; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_apscheduler_djangojobexecution
    ADD CONSTRAINT unique_job_executions UNIQUE (job_id, run_time);


--
-- Name: app_activitylog_user_id_8f1ca209; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX app_activitylog_user_id_8f1ca209 ON public.app_activitylog USING btree (user_id);


--
-- Name: app_adminpermission_codename_6049a330_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX app_adminpermission_codename_6049a330_like ON public.app_adminpermission USING btree (codename varchar_pattern_ops);


--
-- Name: app_adminpermission_name_43484e9f_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX app_adminpermission_name_43484e9f_like ON public.app_adminpermission USING btree (name varchar_pattern_ops);


--
-- Name: app_badstockreport_reported_by_id_6dcea3d3; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX app_badstockreport_reported_by_id_6dcea3d3 ON public.app_badstockreport USING btree (reported_by_id);


--
-- Name: app_badstockreport_supply_id_86415ffb; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX app_badstockreport_supply_id_86415ffb ON public.app_badstockreport USING btree (supply_id);


--
-- Name: app_borrowrequest_property_id_bb32f514; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX app_borrowrequest_property_id_bb32f514 ON public.app_borrowrequest USING btree (property_id);


--
-- Name: app_borrowrequest_user_id_61e85e70; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX app_borrowrequest_user_id_61e85e70 ON public.app_borrowrequest USING btree (user_id);


--
-- Name: app_borrowrequestbatch_approved_by_id_9f9eaece; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX app_borrowrequestbatch_approved_by_id_9f9eaece ON public.app_borrowrequestbatch USING btree (approved_by_id);


--
-- Name: app_borrowrequestbatch_claimed_by_id_2e0ca648; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX app_borrowrequestbatch_claimed_by_id_2e0ca648 ON public.app_borrowrequestbatch USING btree (claimed_by_id);


--
-- Name: app_borrowrequestbatch_user_id_c0a001d8; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX app_borrowrequestbatch_user_id_c0a001d8 ON public.app_borrowrequestbatch USING btree (user_id);


--
-- Name: app_borrowrequestbatch_voided_by_id_f8838fa1; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX app_borrowrequestbatch_voided_by_id_f8838fa1 ON public.app_borrowrequestbatch USING btree (voided_by_id);


--
-- Name: app_borrowrequestitem_batch_request_id_6c874090; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX app_borrowrequestitem_batch_request_id_6c874090 ON public.app_borrowrequestitem USING btree (batch_request_id);


--
-- Name: app_borrowrequestitem_property_id_7bf5ad98; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX app_borrowrequestitem_property_id_7bf5ad98 ON public.app_borrowrequestitem USING btree (property_id);


--
-- Name: app_damagereport_deleted_by_id_35907c84; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX app_damagereport_deleted_by_id_35907c84 ON public.app_damagereport USING btree (deleted_by_id);


--
-- Name: app_damagereport_item_id_99f466ac; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX app_damagereport_item_id_99f466ac ON public.app_damagereport USING btree (item_id);


--
-- Name: app_damagereport_user_id_3adeb816; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX app_damagereport_user_id_3adeb816 ON public.app_damagereport USING btree (user_id);


--
-- Name: app_department_name_476441df_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX app_department_name_476441df_like ON public.app_department USING btree (name varchar_pattern_ops);


--
-- Name: app_lostitem_item_id_c55518a0; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX app_lostitem_item_id_c55518a0 ON public.app_lostitem USING btree (item_id);


--
-- Name: app_lostitem_user_id_58b97a66; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX app_lostitem_user_id_58b97a66 ON public.app_lostitem USING btree (user_id);


--
-- Name: app_notification_user_id_6ab9311d; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX app_notification_user_id_6ab9311d ON public.app_notification USING btree (user_id);


--
-- Name: app_ppmp_department_id_8bea141b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX app_ppmp_department_id_8bea141b ON public.app_ppmp USING btree (department_id);


--
-- Name: app_ppmp_uploaded_by_id_b59105c2; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX app_ppmp_uploaded_by_id_b59105c2 ON public.app_ppmp USING btree (uploaded_by_id);


--
-- Name: app_ppmpitem_ppmp_id_95a31bd0; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX app_ppmpitem_ppmp_id_95a31bd0 ON public.app_ppmpitem USING btree (ppmp_id);


--
-- Name: app_ppmpitemrelease_ppmp_item_id_0ad9480d; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX app_ppmpitemrelease_ppmp_item_id_0ad9480d ON public.app_ppmpitemrelease USING btree (ppmp_item_id);


--
-- Name: app_ppmpitemrelease_released_by_id_45ebd173; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX app_ppmpitemrelease_released_by_id_45ebd173 ON public.app_ppmpitemrelease USING btree (released_by_id);


--
-- Name: app_ppmpitemrelease_supply_request_id_9f317c2a; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX app_ppmpitemrelease_supply_request_id_9f317c2a ON public.app_ppmpitemrelease USING btree (supply_request_id);


--
-- Name: app_ppmpitemrelease_supply_request_item_id_a7106825; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX app_ppmpitemrelease_supply_request_item_id_a7106825 ON public.app_ppmpitemrelease USING btree (supply_request_item_id);


--
-- Name: app_property_barcode_431a43d6_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX app_property_barcode_431a43d6_like ON public.app_property USING btree (barcode varchar_pattern_ops);


--
-- Name: app_property_category_id_eae9fb66; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX app_property_category_id_eae9fb66 ON public.app_property USING btree (category_id);


--
-- Name: app_property_property_number_b046322c_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX app_property_property_number_b046322c_like ON public.app_property USING btree (property_number varchar_pattern_ops);


--
-- Name: app_propertycategory_name_e1e355e2_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX app_propertycategory_name_e1e355e2_like ON public.app_propertycategory USING btree (name varchar_pattern_ops);


--
-- Name: app_propertyhistory_property_id_10a8134a; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX app_propertyhistory_property_id_10a8134a ON public.app_propertyhistory USING btree (property_id);


--
-- Name: app_propertyhistory_user_id_2257a8fb; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX app_propertyhistory_user_id_2257a8fb ON public.app_propertyhistory USING btree (user_id);


--
-- Name: app_propertyppmpallocation_allocated_by_id_9bba64df; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX app_propertyppmpallocation_allocated_by_id_9bba64df ON public.app_propertyppmpallocation USING btree (allocated_by_id);


--
-- Name: app_propertyppmpallocation_ppmp_item_id_71ea6795; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX app_propertyppmpallocation_ppmp_item_id_71ea6795 ON public.app_propertyppmpallocation USING btree (ppmp_item_id);


--
-- Name: app_propertyppmpallocation_property_id_6430cd21; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX app_propertyppmpallocation_property_id_6430cd21 ON public.app_propertyppmpallocation USING btree (property_id);


--
-- Name: app_reservation_batch_id_126de000; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX app_reservation_batch_id_126de000 ON public.app_reservation USING btree (batch_id);


--
-- Name: app_reservation_batch_id_126de000_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX app_reservation_batch_id_126de000_like ON public.app_reservation USING btree (batch_id varchar_pattern_ops);


--
-- Name: app_reservation_generated_borrow_batch_id_cf65df16; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX app_reservation_generated_borrow_batch_id_cf65df16 ON public.app_reservation USING btree (generated_borrow_batch_id);


--
-- Name: app_reservation_item_id_c6ca06dd; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX app_reservation_item_id_c6ca06dd ON public.app_reservation USING btree (item_id);


--
-- Name: app_reservation_user_id_f556cd2c; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX app_reservation_user_id_f556cd2c ON public.app_reservation USING btree (user_id);


--
-- Name: app_reservationbatch_generated_borrow_batch_id_a1efbd23; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX app_reservationbatch_generated_borrow_batch_id_a1efbd23 ON public.app_reservationbatch USING btree (generated_borrow_batch_id);


--
-- Name: app_reservationbatch_user_id_69c9d237; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX app_reservationbatch_user_id_69c9d237 ON public.app_reservationbatch USING btree (user_id);


--
-- Name: app_reservationbatch_voided_by_id_5562353e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX app_reservationbatch_voided_by_id_5562353e ON public.app_reservationbatch USING btree (voided_by_id);


--
-- Name: app_reservationitem_batch_request_id_132e6f10; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX app_reservationitem_batch_request_id_132e6f10 ON public.app_reservationitem USING btree (batch_request_id);


--
-- Name: app_reservationitem_property_id_3e0e17e8; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX app_reservationitem_property_id_3e0e17e8 ON public.app_reservationitem USING btree (property_id);


--
-- Name: app_supply_barcode_eedeb821_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX app_supply_barcode_eedeb821_like ON public.app_supply USING btree (barcode varchar_pattern_ops);


--
-- Name: app_supply_category_id_4b91f056; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX app_supply_category_id_4b91f056 ON public.app_supply USING btree (category_id);


--
-- Name: app_supply_subcategory_id_95c26c3f; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX app_supply_subcategory_id_95c26c3f ON public.app_supply USING btree (subcategory_id);


--
-- Name: app_supplycategory_name_de6ea6f6_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX app_supplycategory_name_de6ea6f6_like ON public.app_supplycategory USING btree (name varchar_pattern_ops);


--
-- Name: app_supplyhistory_supply_id_92bebdbb; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX app_supplyhistory_supply_id_92bebdbb ON public.app_supplyhistory USING btree (supply_id);


--
-- Name: app_supplyhistory_user_id_53322617; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX app_supplyhistory_user_id_53322617 ON public.app_supplyhistory USING btree (user_id);


--
-- Name: app_supplyrequest_supply_id_1544f67e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX app_supplyrequest_supply_id_1544f67e ON public.app_supplyrequest USING btree (supply_id);


--
-- Name: app_supplyrequest_user_id_e3c06aa5; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX app_supplyrequest_user_id_e3c06aa5 ON public.app_supplyrequest USING btree (user_id);


--
-- Name: app_supplyrequestbatch_approved_by_id_799e890f; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX app_supplyrequestbatch_approved_by_id_799e890f ON public.app_supplyrequestbatch USING btree (approved_by_id);


--
-- Name: app_supplyrequestbatch_claimed_by_id_6b0a46ff; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX app_supplyrequestbatch_claimed_by_id_6b0a46ff ON public.app_supplyrequestbatch USING btree (claimed_by_id);


--
-- Name: app_supplyrequestbatch_user_id_41baf4dc; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX app_supplyrequestbatch_user_id_41baf4dc ON public.app_supplyrequestbatch USING btree (user_id);


--
-- Name: app_supplyrequestbatch_voided_by_id_7a670b5e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX app_supplyrequestbatch_voided_by_id_7a670b5e ON public.app_supplyrequestbatch USING btree (voided_by_id);


--
-- Name: app_supplyrequestitem_batch_request_id_83598bed; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX app_supplyrequestitem_batch_request_id_83598bed ON public.app_supplyrequestitem USING btree (batch_request_id);


--
-- Name: app_supplyrequestitem_ppmp_item_id_4be94d51; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX app_supplyrequestitem_ppmp_item_id_4be94d51 ON public.app_supplyrequestitem USING btree (ppmp_item_id);


--
-- Name: app_supplyrequestitem_supply_id_10cc4270; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX app_supplyrequestitem_supply_id_10cc4270 ON public.app_supplyrequestitem USING btree (supply_id);


--
-- Name: app_supplysubcategory_name_61dc2d7b_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX app_supplysubcategory_name_61dc2d7b_like ON public.app_supplysubcategory USING btree (name varchar_pattern_ops);


--
-- Name: app_userprofile_admin_permissions_adminpermission_id_9949964e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX app_userprofile_admin_permissions_adminpermission_id_9949964e ON public.app_userprofile_admin_permissions USING btree (adminpermission_id);


--
-- Name: app_userprofile_admin_permissions_userprofile_id_ebfc8c85; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX app_userprofile_admin_permissions_userprofile_id_ebfc8c85 ON public.app_userprofile_admin_permissions USING btree (userprofile_id);


--
-- Name: app_userprofile_department_id_54b35137; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX app_userprofile_department_id_54b35137 ON public.app_userprofile USING btree (department_id);


--
-- Name: app_usersession_session_key_007734cf_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX app_usersession_session_key_007734cf_like ON public.app_usersession USING btree (session_key varchar_pattern_ops);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_apscheduler_djangojob_next_run_time_2f022619; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_apscheduler_djangojob_next_run_time_2f022619 ON public.django_apscheduler_djangojob USING btree (next_run_time);


--
-- Name: django_apscheduler_djangojobexecution_job_id_daf5090a; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_apscheduler_djangojobexecution_job_id_daf5090a ON public.django_apscheduler_djangojobexecution USING btree (job_id);


--
-- Name: django_apscheduler_djangojobexecution_run_time_16edd96b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_apscheduler_djangojobexecution_run_time_16edd96b ON public.django_apscheduler_djangojobexecution USING btree (run_time);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: app_activitylog app_activitylog_user_id_8f1ca209_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_activitylog
    ADD CONSTRAINT app_activitylog_user_id_8f1ca209_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: app_badstockreport app_badstockreport_reported_by_id_6dcea3d3_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_badstockreport
    ADD CONSTRAINT app_badstockreport_reported_by_id_6dcea3d3_fk_auth_user_id FOREIGN KEY (reported_by_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: app_badstockreport app_badstockreport_supply_id_86415ffb_fk_app_supply_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_badstockreport
    ADD CONSTRAINT app_badstockreport_supply_id_86415ffb_fk_app_supply_id FOREIGN KEY (supply_id) REFERENCES public.app_supply(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: app_borrowrequest app_borrowrequest_property_id_bb32f514_fk_app_property_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_borrowrequest
    ADD CONSTRAINT app_borrowrequest_property_id_bb32f514_fk_app_property_id FOREIGN KEY (property_id) REFERENCES public.app_property(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: app_borrowrequest app_borrowrequest_user_id_61e85e70_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_borrowrequest
    ADD CONSTRAINT app_borrowrequest_user_id_61e85e70_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: app_borrowrequestbatch app_borrowrequestbatch_approved_by_id_9f9eaece_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_borrowrequestbatch
    ADD CONSTRAINT app_borrowrequestbatch_approved_by_id_9f9eaece_fk_auth_user_id FOREIGN KEY (approved_by_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: app_borrowrequestbatch app_borrowrequestbatch_claimed_by_id_2e0ca648_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_borrowrequestbatch
    ADD CONSTRAINT app_borrowrequestbatch_claimed_by_id_2e0ca648_fk_auth_user_id FOREIGN KEY (claimed_by_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: app_borrowrequestbatch app_borrowrequestbatch_user_id_c0a001d8_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_borrowrequestbatch
    ADD CONSTRAINT app_borrowrequestbatch_user_id_c0a001d8_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: app_borrowrequestbatch app_borrowrequestbatch_voided_by_id_f8838fa1_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_borrowrequestbatch
    ADD CONSTRAINT app_borrowrequestbatch_voided_by_id_f8838fa1_fk_auth_user_id FOREIGN KEY (voided_by_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: app_borrowrequestitem app_borrowrequestite_batch_request_id_6c874090_fk_app_borro; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_borrowrequestitem
    ADD CONSTRAINT app_borrowrequestite_batch_request_id_6c874090_fk_app_borro FOREIGN KEY (batch_request_id) REFERENCES public.app_borrowrequestbatch(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: app_borrowrequestitem app_borrowrequestitem_property_id_7bf5ad98_fk_app_property_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_borrowrequestitem
    ADD CONSTRAINT app_borrowrequestitem_property_id_7bf5ad98_fk_app_property_id FOREIGN KEY (property_id) REFERENCES public.app_property(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: app_damagereport app_damagereport_deleted_by_id_35907c84_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_damagereport
    ADD CONSTRAINT app_damagereport_deleted_by_id_35907c84_fk_auth_user_id FOREIGN KEY (deleted_by_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: app_damagereport app_damagereport_item_id_99f466ac_fk_app_property_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_damagereport
    ADD CONSTRAINT app_damagereport_item_id_99f466ac_fk_app_property_id FOREIGN KEY (item_id) REFERENCES public.app_property(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: app_damagereport app_damagereport_user_id_3adeb816_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_damagereport
    ADD CONSTRAINT app_damagereport_user_id_3adeb816_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: app_lostitem app_lostitem_item_id_c55518a0_fk_app_property_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_lostitem
    ADD CONSTRAINT app_lostitem_item_id_c55518a0_fk_app_property_id FOREIGN KEY (item_id) REFERENCES public.app_property(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: app_lostitem app_lostitem_user_id_58b97a66_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_lostitem
    ADD CONSTRAINT app_lostitem_user_id_58b97a66_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: app_notification app_notification_user_id_6ab9311d_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_notification
    ADD CONSTRAINT app_notification_user_id_6ab9311d_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: app_ppmp app_ppmp_department_id_8bea141b_fk_app_department_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_ppmp
    ADD CONSTRAINT app_ppmp_department_id_8bea141b_fk_app_department_id FOREIGN KEY (department_id) REFERENCES public.app_department(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: app_ppmp app_ppmp_uploaded_by_id_b59105c2_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_ppmp
    ADD CONSTRAINT app_ppmp_uploaded_by_id_b59105c2_fk_auth_user_id FOREIGN KEY (uploaded_by_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: app_ppmpitem app_ppmpitem_ppmp_id_95a31bd0_fk_app_ppmp_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_ppmpitem
    ADD CONSTRAINT app_ppmpitem_ppmp_id_95a31bd0_fk_app_ppmp_id FOREIGN KEY (ppmp_id) REFERENCES public.app_ppmp(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: app_ppmpitemrelease app_ppmpitemrelease_ppmp_item_id_0ad9480d_fk_app_ppmpitem_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_ppmpitemrelease
    ADD CONSTRAINT app_ppmpitemrelease_ppmp_item_id_0ad9480d_fk_app_ppmpitem_id FOREIGN KEY (ppmp_item_id) REFERENCES public.app_ppmpitem(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: app_ppmpitemrelease app_ppmpitemrelease_released_by_id_45ebd173_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_ppmpitemrelease
    ADD CONSTRAINT app_ppmpitemrelease_released_by_id_45ebd173_fk_auth_user_id FOREIGN KEY (released_by_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: app_ppmpitemrelease app_ppmpitemrelease_supply_request_id_9f317c2a_fk_app_suppl; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_ppmpitemrelease
    ADD CONSTRAINT app_ppmpitemrelease_supply_request_id_9f317c2a_fk_app_suppl FOREIGN KEY (supply_request_id) REFERENCES public.app_supplyrequest(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: app_ppmpitemrelease app_ppmpitemrelease_supply_request_item__a7106825_fk_app_suppl; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_ppmpitemrelease
    ADD CONSTRAINT app_ppmpitemrelease_supply_request_item__a7106825_fk_app_suppl FOREIGN KEY (supply_request_item_id) REFERENCES public.app_supplyrequestitem(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: app_property app_property_category_id_eae9fb66_fk_app_propertycategory_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_property
    ADD CONSTRAINT app_property_category_id_eae9fb66_fk_app_propertycategory_id FOREIGN KEY (category_id) REFERENCES public.app_propertycategory(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: app_propertyhistory app_propertyhistory_property_id_10a8134a_fk_app_property_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_propertyhistory
    ADD CONSTRAINT app_propertyhistory_property_id_10a8134a_fk_app_property_id FOREIGN KEY (property_id) REFERENCES public.app_property(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: app_propertyhistory app_propertyhistory_user_id_2257a8fb_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_propertyhistory
    ADD CONSTRAINT app_propertyhistory_user_id_2257a8fb_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: app_propertyppmpallocation app_propertyppmpallo_allocated_by_id_9bba64df_fk_auth_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_propertyppmpallocation
    ADD CONSTRAINT app_propertyppmpallo_allocated_by_id_9bba64df_fk_auth_user FOREIGN KEY (allocated_by_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: app_propertyppmpallocation app_propertyppmpallo_ppmp_item_id_71ea6795_fk_app_ppmpi; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_propertyppmpallocation
    ADD CONSTRAINT app_propertyppmpallo_ppmp_item_id_71ea6795_fk_app_ppmpi FOREIGN KEY (ppmp_item_id) REFERENCES public.app_ppmpitem(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: app_propertyppmpallocation app_propertyppmpallo_property_id_6430cd21_fk_app_prope; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_propertyppmpallocation
    ADD CONSTRAINT app_propertyppmpallo_property_id_6430cd21_fk_app_prope FOREIGN KEY (property_id) REFERENCES public.app_property(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: app_reservation app_reservation_generated_borrow_bat_cf65df16_fk_app_borro; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_reservation
    ADD CONSTRAINT app_reservation_generated_borrow_bat_cf65df16_fk_app_borro FOREIGN KEY (generated_borrow_batch_id) REFERENCES public.app_borrowrequestbatch(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: app_reservation app_reservation_item_id_c6ca06dd_fk_app_property_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_reservation
    ADD CONSTRAINT app_reservation_item_id_c6ca06dd_fk_app_property_id FOREIGN KEY (item_id) REFERENCES public.app_property(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: app_reservation app_reservation_user_id_f556cd2c_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_reservation
    ADD CONSTRAINT app_reservation_user_id_f556cd2c_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: app_reservationbatch app_reservationbatch_generated_borrow_bat_a1efbd23_fk_app_borro; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_reservationbatch
    ADD CONSTRAINT app_reservationbatch_generated_borrow_bat_a1efbd23_fk_app_borro FOREIGN KEY (generated_borrow_batch_id) REFERENCES public.app_borrowrequestbatch(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: app_reservationbatch app_reservationbatch_user_id_69c9d237_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_reservationbatch
    ADD CONSTRAINT app_reservationbatch_user_id_69c9d237_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: app_reservationbatch app_reservationbatch_voided_by_id_5562353e_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_reservationbatch
    ADD CONSTRAINT app_reservationbatch_voided_by_id_5562353e_fk_auth_user_id FOREIGN KEY (voided_by_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: app_reservationitem app_reservationitem_batch_request_id_132e6f10_fk_app_reser; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_reservationitem
    ADD CONSTRAINT app_reservationitem_batch_request_id_132e6f10_fk_app_reser FOREIGN KEY (batch_request_id) REFERENCES public.app_reservationbatch(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: app_reservationitem app_reservationitem_property_id_3e0e17e8_fk_app_property_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_reservationitem
    ADD CONSTRAINT app_reservationitem_property_id_3e0e17e8_fk_app_property_id FOREIGN KEY (property_id) REFERENCES public.app_property(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: app_supply app_supply_category_id_4b91f056_fk_app_supplycategory_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_supply
    ADD CONSTRAINT app_supply_category_id_4b91f056_fk_app_supplycategory_id FOREIGN KEY (category_id) REFERENCES public.app_supplycategory(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: app_supply app_supply_subcategory_id_95c26c3f_fk_app_supplysubcategory_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_supply
    ADD CONSTRAINT app_supply_subcategory_id_95c26c3f_fk_app_supplysubcategory_id FOREIGN KEY (subcategory_id) REFERENCES public.app_supplysubcategory(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: app_supplyhistory app_supplyhistory_supply_id_92bebdbb_fk_app_supply_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_supplyhistory
    ADD CONSTRAINT app_supplyhistory_supply_id_92bebdbb_fk_app_supply_id FOREIGN KEY (supply_id) REFERENCES public.app_supply(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: app_supplyhistory app_supplyhistory_user_id_53322617_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_supplyhistory
    ADD CONSTRAINT app_supplyhistory_user_id_53322617_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: app_supplyquantity app_supplyquantity_supply_id_35fbefbe_fk_app_supply_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_supplyquantity
    ADD CONSTRAINT app_supplyquantity_supply_id_35fbefbe_fk_app_supply_id FOREIGN KEY (supply_id) REFERENCES public.app_supply(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: app_supplyrequest app_supplyrequest_supply_id_1544f67e_fk_app_supply_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_supplyrequest
    ADD CONSTRAINT app_supplyrequest_supply_id_1544f67e_fk_app_supply_id FOREIGN KEY (supply_id) REFERENCES public.app_supply(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: app_supplyrequest app_supplyrequest_user_id_e3c06aa5_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_supplyrequest
    ADD CONSTRAINT app_supplyrequest_user_id_e3c06aa5_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: app_supplyrequestbatch app_supplyrequestbatch_approved_by_id_799e890f_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_supplyrequestbatch
    ADD CONSTRAINT app_supplyrequestbatch_approved_by_id_799e890f_fk_auth_user_id FOREIGN KEY (approved_by_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: app_supplyrequestbatch app_supplyrequestbatch_claimed_by_id_6b0a46ff_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_supplyrequestbatch
    ADD CONSTRAINT app_supplyrequestbatch_claimed_by_id_6b0a46ff_fk_auth_user_id FOREIGN KEY (claimed_by_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: app_supplyrequestbatch app_supplyrequestbatch_user_id_41baf4dc_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_supplyrequestbatch
    ADD CONSTRAINT app_supplyrequestbatch_user_id_41baf4dc_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: app_supplyrequestbatch app_supplyrequestbatch_voided_by_id_7a670b5e_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_supplyrequestbatch
    ADD CONSTRAINT app_supplyrequestbatch_voided_by_id_7a670b5e_fk_auth_user_id FOREIGN KEY (voided_by_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: app_supplyrequestitem app_supplyrequestite_batch_request_id_83598bed_fk_app_suppl; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_supplyrequestitem
    ADD CONSTRAINT app_supplyrequestite_batch_request_id_83598bed_fk_app_suppl FOREIGN KEY (batch_request_id) REFERENCES public.app_supplyrequestbatch(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: app_supplyrequestitem app_supplyrequestitem_ppmp_item_id_4be94d51_fk_app_ppmpitem_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_supplyrequestitem
    ADD CONSTRAINT app_supplyrequestitem_ppmp_item_id_4be94d51_fk_app_ppmpitem_id FOREIGN KEY (ppmp_item_id) REFERENCES public.app_ppmpitem(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: app_supplyrequestitem app_supplyrequestitem_supply_id_10cc4270_fk_app_supply_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_supplyrequestitem
    ADD CONSTRAINT app_supplyrequestitem_supply_id_10cc4270_fk_app_supply_id FOREIGN KEY (supply_id) REFERENCES public.app_supply(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: app_userprofile_admin_permissions app_userprofile_admi_adminpermission_id_9949964e_fk_app_admin; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_userprofile_admin_permissions
    ADD CONSTRAINT app_userprofile_admi_adminpermission_id_9949964e_fk_app_admin FOREIGN KEY (adminpermission_id) REFERENCES public.app_adminpermission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: app_userprofile_admin_permissions app_userprofile_admi_userprofile_id_ebfc8c85_fk_app_userp; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_userprofile_admin_permissions
    ADD CONSTRAINT app_userprofile_admi_userprofile_id_ebfc8c85_fk_app_userp FOREIGN KEY (userprofile_id) REFERENCES public.app_userprofile(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: app_userprofile app_userprofile_department_id_54b35137_fk_app_department_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_userprofile
    ADD CONSTRAINT app_userprofile_department_id_54b35137_fk_app_department_id FOREIGN KEY (department_id) REFERENCES public.app_department(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: app_userprofile app_userprofile_user_id_370bd89d_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_userprofile
    ADD CONSTRAINT app_userprofile_user_id_370bd89d_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: app_usersession app_usersession_user_id_0e017a61_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_usersession
    ADD CONSTRAINT app_usersession_user_id_0e017a61_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_apscheduler_djangojobexecution django_apscheduler_djangojobexecution_job_id_daf5090a_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_apscheduler_djangojobexecution
    ADD CONSTRAINT django_apscheduler_djangojobexecution_job_id_daf5090a_fk FOREIGN KEY (job_id) REFERENCES public.django_apscheduler_djangojob(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict 1z9fbfo1Ymf1sTOgNL2odt8fmdGxNJZRfNWSLh4pL1qNKnjJiaEcKZmUOPE1gQ5

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
1pbkdf2_sha256$1000000$CddNQ5oFrwFF1EjWsWYtkW$XNiGALDVbrOqDk5PEysxPn5ny/UVY4u8c5zaE3G9h1E=\NtADMINtt2026-06-27 00:00:00+00
2pbkdf2_sha256$1000000$oA55rPxOBQr8zmlbE4VwLT$6VH4nECFN+0SBGQ1XYNFwI/5NczVPE+PmS9V/JkBtSc=\NfUSERft2026-06-27 00:00:00+00
\.

COPY public.app_userprofile (id, role, department_id, phone, user_id, designation, auto_enable_at, must_change_password, has_limited_access) FROM stdin;
1ADMIN\N\N1\N\Nff
2USER\N\N2\N\Nff
\.

SELECT pg_catalog.setval('public.auth_user_id_seq', 2, true);
SELECT pg_catalog.setval('public.app_userprofile_id_seq', 2, true);
