# Generated by Django 5.2 on 2025-04-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userprofile_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='assigned_to',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
