# Generated by Django 5.1.3 on 2025-05-23 05:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_property_assigned_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='property',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='property',
            name='available_for_request',
        ),
        migrations.RemoveField(
            model_name='property',
            name='date_acquired',
        ),
        migrations.RemoveField(
            model_name='property',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='property',
            name='category',
            field=models.CharField(blank=True, choices=[('Office Equipment', 'Office Equipment'), ('ICT Equipment', 'ICT Equipment'), ('Communication Equipment', 'Communication Equipment'), ('Other Machinery and Equipment', 'Other Machinery and Equipment'), ('Furniture and Fixtures', 'Furniture and Fixtures')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='unit_of_measure',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='unit_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='property',
            name='barcode',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='condition',
            field=models.CharField(blank=True, choices=[('In good condition', 'In good condition'), ('Needing repair', 'Needing repair'), ('Unserviceable', 'Unserviceable'), ('Obsolete', 'Obsolete'), ('No longer needed', 'No longer needed'), ('Not used since purchased', 'Not used since purchased')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted')], max_length=10)),
                ('model_name', models.CharField(max_length=100)),
                ('object_repr', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
