# Generated by Django 5.2.1 on 2025-05-24 05:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_property_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='needed_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
