# Generated by Django 5.2.1 on 2025-05-24 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_reservation_needed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='needed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
