# Generated by Django 5.2.1 on 2025-05-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_borrowrequest_remarks_damagereport_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
