# Generated by Django 5.2 on 2025-05-28 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_notification_remarks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supply',
            options={'permissions': [('view_dashboard', 'Can view dashboard')]},
        ),
    ]
