# Generated by Django 5.2 on 2025-05-28 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_supply_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supply',
            options={'permissions': [('view_admin_dashboard', 'Can view  admin dashboard'), ('view_user_dashboard', 'Can view user dashboard'), ('view_checkout_page', 'Can view checkout page')]},
        ),
    ]
