# Generated by Django 5.2.1 on 2025-05-28 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_supply_quantity_supplyquantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supply',
            name='status',
        ),
        migrations.AddField(
            model_name='property',
            name='availability',
            field=models.CharField(choices=[('available', 'Available'), ('not_available', 'Not Available')], default='available', max_length=20),
        ),
    ]
