# Generated by Django 5.2.1 on 2025-05-29 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_supply_status_property_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supply',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('common_office', 'COMMON OFFICE SUPPLIES AND MATERIALS'), ('filing', 'FILING SUPPLIES AND MATERIALS'), ('ribbons', 'RIBBONS, INKS, TONERS AND CARTRIDGES'), ('paper', 'PAPER PRODUCTS'), ('university_activity', 'OTHER UNIVERSITY ACTIVITY 1 (CSG Activity)'), ('printed_journals', 'PRINTED JOURNALS'), ('common_cleaning', 'COMMON CLEANING SUPPLIES AND MATERIALS'), ('other_supplies', 'OTHER SUPPLIES AND MATERIALS'), ('electrical', 'ELECTRICAL, LIGHTING FIXTURES, TOOLS AND ACCESSORIES'), ('kitchen', 'KITCHEN SUPPLIES AND MATERIALS'), ('common_office_supplies', 'COMMON OFFICE SUPPLIES'), ('cleaning_supplies', 'CLEANING SUPPLIES AND MATERIALS'), ('covid_supplies', 'COVID RECOVERY SUPPLIES'), ('electrical_supplies', 'ELECTRICAL SUPPLIES AND MATERIALS')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('active', 'Active'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='supply',
            name='category',
            field=models.CharField(blank=True, choices=[('office_supplies', 'Office Supplies Expenses'), ('textbooks', 'Textbooks and Instructional Materials Expenses'), ('other_supplies', 'Other Supplies & Materials Expenses')], max_length=100, null=True),
        ),
    ]
