# Generated by Django 5.2 on 2025-05-29 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_userprofile_role'),
        ('app', '0018_remove_supply_status_property_availability'),
    ]

    operations = [
    ]
