# Generated by Django 5.2.1 on 2025-05-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_supply_description_supply_subcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
