# Generated by Django 5.2.1 on 2025-05-29 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_supply_expiration_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('login', 'Logged In'), ('logout', 'Logged Out'), ('view', 'Viewed'), ('request', 'Requested'), ('approve', 'Approved'), ('reject', 'Rejected'), ('borrow', 'Borrowed'), ('return', 'Returned'), ('report', 'Reported')], max_length=10),
        ),
    ]
