# Generated by Django 5.2 on 2025-05-30 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_propertyhistory_supplyhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyhistory',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplyhistory',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
