# Generated by Django 5.2 on 2025-05-30 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_property_original_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='original_quantity',
        ),
    ]
