# Generated by Django 5.2 on 2025-05-30 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_remove_property_original_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='original_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
