# Generated by Django 5.2 on 2025-05-31 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_property_original_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='original_quantity',
        ),
        migrations.RemoveField(
            model_name='supplyquantity',
            name='original_quantity',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('USER', 'USER')], max_length=20),
        ),
    ]
