# Generated by Django 5.2 on 2025-05-31 15:29

from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_property_overall_quantity_property_property_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='overall_quantity',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
