# Generated by Django 5.2 on 2025-05-31 16:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20250531_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='condition',
            field=models.CharField(choices=[('In good condition', 'In good condition'), ('Needing repair', 'Needing repair'), ('Unserviceable', 'Unserviceable'), ('Obsolete', 'Obsolete'), ('No longer needed', 'No longer needed'), ('Not used since purchased', 'Not used since purchased')], default='In good condition', max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='overall_quantity',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='quantity',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
