# Generated by Django 5.2 on 2025-05-31 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_userprofile_disable_date_userprofile_disable_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='disable_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='disable_reason',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='disabled_by',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='enable_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_temporarily_disabled',
        ),
    ]
