# Generated by Django 5.2 on 2025-06-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_supply_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('returned', 'Returned'), ('overdue', 'Overdue'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
