# Generated by Django 5.2.1 on 2025-06-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_alter_borrowrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('returned', 'Returned'), ('overdue', 'Overdue'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
    ]
