# Generated by Django 5.2.1 on 2025-06-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_alter_supplycategory_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='supplysubcategory',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='supplycategory',
            name='description',
        ),
        migrations.AlterField(
            model_name='supplysubcategory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.RemoveField(
            model_name='supplysubcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='supplysubcategory',
            name='description',
        ),
    ]
