# Generated by Django 5.2.1 on 2025-06-02 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_supplycategory_alter_supply_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplysubcategory',
            name='category',
        ),
    ]
