# Generated by Django 5.2.1 on 2025-06-04 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_alter_supply_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supply',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
