# Generated by Django 5.2 on 2025-06-02 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_remove_supplysubcategory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplysubcategory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='app.supplycategory'),
        ),
    ]
