# Generated by Django 5.2.1 on 2025-08-25 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_property_is_archived_supply_is_archived'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyRequestBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('purpose', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('partially_approved', 'Partially Approved')], default='pending', max_length=20)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-request_date'],
            },
        ),
        migrations.CreateModel(
            name='SupplyRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('approved', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('batch_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.supplyrequestbatch')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.supply')),
            ],
            options={
                'unique_together': {('batch_request', 'supply')},
            },
        ),
    ]
