# Generated by Django 5.2.1 on 2025-08-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_supplyrequestbatch_supplyrequestitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplyrequestitem',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
