# Generated by Django 5.2.1 on 2025-08-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_supplyrequestitem_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplyrequestitem',
            name='quantity_deducted',
            field=models.BooleanField(default=False),
        ),
    ]
