# Generated by Django 5.2.1 on 2025-08-28 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_supplyrequestitem_quantity_deducted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplyrequestitem',
            name='quantity_deducted',
        ),
    ]
