# Generated by Django 5.2.1 on 2025-08-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_add_processed_field_to_supply_request_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplyrequestitem',
            name='processed',
        ),
        migrations.AddField(
            model_name='supplyrequestitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
