# Generated by Django 5.2.1 on 2025-08-28 16:02

from django.db import migrations


def set_initial_status(apps, schema_editor):
    """
    Set initial status values for existing SupplyRequestItem records.
    For approved items, set status to 'approved'.
    For non-approved items, set status to 'pending' (not 'rejected' since we don't know if they were explicitly rejected).
    """
    SupplyRequestItem = apps.get_model('app', 'SupplyRequestItem')
    
    # Update approved items
    SupplyRequestItem.objects.filter(approved=True).update(status='approved')
    
    # Update non-approved items to pending (assuming they weren't explicitly rejected)
    SupplyRequestItem.objects.filter(approved=False).update(status='pending')


def reverse_set_initial_status(apps, schema_editor):
    """
    Reverse migration - reset status to pending for all items.
    """
    SupplyRequestItem = apps.get_model('app', 'SupplyRequestItem')
    SupplyRequestItem.objects.all().update(status='pending')


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_remove_supplyrequestitem_processed_and_more'),
    ]

    operations = [
        migrations.RunPython(set_initial_status, reverse_set_initial_status),
    ]
