# Generated by Django 5.2.1 on 2025-08-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_auto_20250829_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplyrequestbatch',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('partially_approved', 'Partially Approved'), ('for_claiming', 'For Claiming')], default='pending', max_length=20),
        ),
    ]
