# Generated by Django 5.2.1 on 2025-08-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_alter_supplyrequestbatch_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplyrequestitem',
            name='approved_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
