# Generated by Django 5.2.1 on 2025-08-29 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_add_claiming_workflow_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('login', 'Logged In'), ('logout', 'Logged Out'), ('view', 'Viewed'), ('request', 'Requested'), ('approve', 'Approved'), ('reject', 'Rejected'), ('claim', 'Claimed'), ('complete', 'Completed'), ('borrow', 'Borrowed'), ('return', 'Returned'), ('report', 'Reported')], max_length=10),
        ),
    ]
