# Generated by Django 5.2.1 on 2025-08-31 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_supplyrequestbatch_claimed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='damagereport',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='report_images/'),
        ),
    ]
