# Generated by Django 5.2.1 on 2025-09-23 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_property_accountable_person_property_year_acquired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='accountable_person',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        # Drop and recreate the year_acquired field to avoid type casting issues
        migrations.RemoveField(
            model_name='property',
            name='year_acquired',
        ),
        migrations.AddField(
            model_name='property',
            name='year_acquired',
            field=models.DateField(blank=True, null=True),
        ),
    ]
