# Generated by Django 5.2.1 on 2025-09-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_alter_property_accountable_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='new_property_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
