# Generated by Django 5.2.1 on 2025-09-28 17:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_add_old_property_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='quantity_per_physical_count',
            field=models.PositiveIntegerField(default=0, help_text='Quantity based on physical count/inventory', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
