# Generated by Django 5.2.1 on 2025-09-26 16:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_property_new_property_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='quantity_per_physical_count',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='property',
            name='quantity_per_property_card',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
