# Generated by Django 5.2.1 on 2025-10-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_reservationbatch_reservationitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationbatch',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('partially_approved', 'Partially Approved'), ('active', 'Active'), ('completed', 'Completed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
