# Generated by Django 5.2.1 on 2025-10-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_alter_reservationbatch_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationitem',
            name='batch_reservation',
        ),
        migrations.RemoveField(
            model_name='reservationitem',
            name='property',
        ),
        migrations.AddField(
            model_name='propertycategory',
            name='uacs',
            field=models.BigIntegerField(blank=True, help_text='UACS Code (e.g., 13124324)', null=True),
        ),
        migrations.DeleteModel(
            name='ReservationBatch',
        ),
        migrations.DeleteModel(
            name='ReservationItem',
        ),
    ]
