# Generated by Django 5.2.1 on 2025-10-09 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_remove_reservationitem_batch_reservation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('login', 'Logged In'), ('logout', 'Logged Out'), ('view', 'Viewed'), ('request', 'Requested'), ('approve', 'Approved'), ('reject', 'Rejected'), ('claim', 'Claimed'), ('complete', 'Completed'), ('borrow', 'Borrowed'), ('return', 'Returned'), ('report', 'Reported'), ('activate', 'Activated'), ('change_password', 'Changed Password')], max_length=50),
        ),
        migrations.AlterField(
            model_name='propertycategory',
            name='uacs',
            field=models.BigIntegerField(blank=True, help_text='UACS (e.g., 13124324)', null=True),
        ),
    ]
