# Generated by Django 5.2.1 on 2025-10-09 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0062_alter_activitylog_action_alter_propertycategory_uacs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='object_repr',
            field=models.CharField(max_length=500),
        ),
    ]
