# Generated by Django 5.2.1 on 2025-10-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0063_alter_activitylog_object_repr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='object_repr',
            field=models.TextField(),
        ),
    ]
