# Generated by Django 5.2.1 on 2025-10-09 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_alter_activitylog_object_repr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='barcode',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='supply',
            name='barcode',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
