# Generated by Django 5.2.1 on 2025-10-09 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0065_alter_property_barcode_alter_supply_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='barcode',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supply',
            name='barcode',
            field=models.TextField(blank=True, null=True),
        ),
    ]
