# Generated by Django 5.2.1 on 2025-10-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0066_alter_property_barcode_alter_supply_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='barcode_image',
            field=models.ImageField(blank=True, null=True, upload_to='barcodes/properties/'),
        ),
        migrations.AddField(
            model_name='supply',
            name='barcode_image',
            field=models.ImageField(blank=True, null=True, upload_to='barcodes/supplies/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='supply',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
