# Generated by Django 5.2.1 on 2025-10-12 15:20

from django.db import migrations
from django.core.files.base import ContentFile
import base64
import re


def convert_barcodes_to_images(apps, schema_editor):
    """
    Convert existing base64 barcode strings to:
    1. Simple text barcode (e.g., "SUP-001", "PROP-123")
    2. Barcode image file
    """
    Supply = apps.get_model('app', 'Supply')
    Property = apps.get_model('app', 'Property')
    
    # Convert Supplies
    for supply in Supply.objects.all():
        if supply.barcode:
            # Check if barcode is base64 (starts with "data:image")
            if supply.barcode.startswith('data:image'):
                # Generate simple barcode text
                barcode_text = f"SUP-{supply.id}"
                
                # Extract base64 data and save as image
                try:
                    # Remove data URI prefix
                    base64_data = re.sub(r'^data:image/\w+;base64,', '', supply.barcode)
                    image_data = base64.b64decode(base64_data)
                    
                    # Save to barcode_image field
                    filename = f"{barcode_text}.png"
                    supply.barcode_image.save(filename, ContentFile(image_data), save=False)
                    
                    # Update barcode to simple text
                    supply.barcode = barcode_text
                    supply.save()
                except Exception as e:
                    print(f"Error converting supply {supply.id} barcode: {e}")
            elif not supply.barcode.startswith('SUP-'):
                # If barcode exists but doesn't follow format, standardize it
                supply.barcode = f"SUP-{supply.id}"
                supply.save()
    
    # Convert Properties
    for prop in Property.objects.all():
        if prop.barcode:
            # Check if barcode is base64 (starts with "data:image")
            if prop.barcode.startswith('data:image'):
                # Use property_number if available, otherwise generate barcode text
                barcode_text = prop.property_number if prop.property_number else f"PROP-{prop.id}"
                
                # Extract base64 data and save as image
                try:
                    # Remove data URI prefix
                    base64_data = re.sub(r'^data:image/\w+;base64,', '', prop.barcode)
                    image_data = base64.b64decode(base64_data)
                    
                    # Save to barcode_image field
                    filename = f"{barcode_text}.png"
                    prop.barcode_image.save(filename, ContentFile(image_data), save=False)
                    
                    # Update barcode to simple text
                    prop.barcode = barcode_text
                    prop.save()
                except Exception as e:
                    print(f"Error converting property {prop.id} barcode: {e}")
            elif prop.property_number and prop.barcode != prop.property_number:
                # Standardize to property_number
                prop.barcode = prop.property_number
                prop.save()
            elif not prop.property_number and not prop.barcode.startswith('PROP-'):
                # Generate standard barcode
                prop.barcode = f"PROP-{prop.id}"
                prop.save()


def reverse_migration(apps, schema_editor):
    """
    Reverse operation: This is optional since we can't perfectly reverse
    the conversion, but we'll clear the barcode_image field
    """
    Supply = apps.get_model('app', 'Supply')
    Property = apps.get_model('app', 'Property')
    
    # Clear barcode images
    Supply.objects.all().update(barcode_image=None)
    Property.objects.all().update(barcode_image=None)


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0067_change_barcode_to_charfield_and_add_image'),
    ]

    operations = [
        migrations.RunPython(convert_barcodes_to_images, reverse_migration),
    ]
