# Generated by Django 5.2.1 on 2025-10-16 17:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0068_convert_base64_barcodes_to_images'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('login', 'Logged In'), ('logout', 'Logged Out'), ('view', 'Viewed'), ('request', 'Requested'), ('approve', 'Approved'), ('reject', 'Rejected'), ('claim', 'Claimed'), ('complete', 'Completed'), ('borrow', 'Borrowed'), ('return', 'Returned'), ('report', 'Reported'), ('activate', 'Activated'), ('change_password', 'Changed Password'), ('bad_stock', 'Bad Stock Removal')], max_length=50),
        ),
        migrations.CreateModel(
            name='BadStockReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_removed', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('remarks', models.TextField()),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bad_stock_reports', to=settings.AUTH_USER_MODEL)),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bad_stock_reports', to='app.supply')),
            ],
            options={
                'ordering': ['-reported_at'],
            },
        ),
    ]
