# Generated by Django 5.2.1 on 2025-10-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0069_alter_activitylog_action_badstockreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplyquantity',
            name='reserved_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
