# Generated by Django 5.2.1 on 2025-11-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0071_userprofile_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='damagereport',
            name='image_format',
            field=models.CharField(blank=True, default='jpeg', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='damagereport',
            name='image',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
