# Generated by Django 5.2.1 on 2025-11-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0072_damagereport_image_format_alter_damagereport_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damagereport',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
