# Generated by Django 5.2.1 on 2025-11-05 03:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0073_alter_damage_report_image_to_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='damagereport',
            name='image_format',
        ),
        migrations.AddField(
            model_name='damagereport',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When the image was deleted', null=True),
        ),
        migrations.AddField(
            model_name='damagereport',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='Admin who deleted the image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_damage_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='damagereport',
            name='image_size',
            field=models.PositiveIntegerField(blank=True, help_text='Image size in bytes', null=True),
        ),
        migrations.AlterField(
            model_name='damagereport',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='report_images/'),
        ),
    ]
