# Generated by Django 5.2.1 on 2025-11-05 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0074_remove_damagereport_image_format_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='damagereport',
            name='image',
        ),
        migrations.AddField(
            model_name='damagereport',
            name='image_data',
            field=models.BinaryField(blank=True, help_text='Compressed image stored as binary data', null=True),
        ),
        migrations.AddField(
            model_name='damagereport',
            name='image_name',
            field=models.CharField(blank=True, help_text='Original filename', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='damagereport',
            name='image_type',
            field=models.CharField(default='image/jpeg', help_text='MIME type (e.g., image/jpeg)', max_length=50),
        ),
    ]
