# Generated by Django 5.2.1 on 2025-11-05 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0075_remove_damagereport_image_damagereport_image_data_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-reservation_date']},
        ),
        migrations.AddField(
            model_name='reservation',
            name='batch_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='batch_request_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
