# Generated by Django 5.2.1 on 2025-11-05 08:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0077_reservationbatch_reservationitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='reserved_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Quantity reserved by pending/approved requests', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
