# Generated by Django 5.2.1 on 2025-11-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0078_property_reserved_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='auto_enable_at',
            field=models.DateTimeField(blank=True, help_text='If set, account will be automatically reactivated at this date/time', null=True),
        ),
    ]
