# Generated by Django 5.2.1 on 2025-11-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0079_userprofile_auto_enable_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequestbatch',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
