# Generated by Django 5.2.1 on 2025-11-11 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0080_borrowrequestbatch_return_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowrequestbatch',
            name='return_date',
        ),
        migrations.AddField(
            model_name='borrowrequestitem',
            name='near_overdue_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='borrowrequestitem',
            name='overdue_notified',
            field=models.BooleanField(default=False),
        ),
    ]
