# Generated by Django 5.2.1 on 2025-11-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0081_remove_borrowrequestbatch_return_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='unit',
            field=models.CharField(choices=[('pcs', 'Pieces'), ('ream', 'Ream'), ('set', 'Set'), ('box', 'Box'), ('pack', 'Pack'), ('roll', 'Roll'), ('dozen', 'Dozen'), ('unit', 'Unit'), ('bottle', 'Bottle'), ('can', 'Can'), ('jar', 'Jar'), ('tube', 'Tube'), ('m', 'Meter'), ('kg', 'Kilogram'), ('l', 'Liter')], default='pcs', max_length=20),
        ),
    ]
