# Generated by Django 5.2.1 on 2025-11-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0083_alter_supply_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
