# Generated by Django 5.2.1 on 2025-11-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0084_alter_supply_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='If True, user must change password on next login'),
        ),
        migrations.AlterField(
            model_name='borrowrequestbatch',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('partially_approved', 'Partially Approved'), ('for_claiming', 'For Claiming'), ('active', 'Active'), ('returned', 'Returned'), ('overdue', 'Overdue'), ('expired', 'Expired'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
