# Generated by Django 5.2.1 on 2025-11-19 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0085_userprofile_must_change_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='serial_number',
            field=models.CharField(blank=True, help_text='Serial number of the property', max_length=100, null=True),
        ),
    ]
