# Generated by Django 5.2.1 on 2025-11-21 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0086_property_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequestitem',
            name='from_reservation',
            field=models.BooleanField(default=False),
        ),
    ]
