# Generated by Django 5.2.1 on 2025-11-26 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0088_usersession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Description of circumstances surrounding the loss')),
                ('last_seen_location', models.CharField(blank=True, help_text='Last known location of the item', max_length=255, null=True)),
                ('last_seen_date', models.DateField(blank=True, help_text='Date when item was last seen', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True, help_text='Admin remarks or notes', null=True)),
                ('report_date', models.DateTimeField(auto_now_add=True)),
                ('image_data', models.BinaryField(blank=True, help_text='Compressed image stored as binary data', null=True)),
                ('image_name', models.CharField(blank=True, help_text='Original filename', max_length=255, null=True)),
                ('image_type', models.CharField(default='image/jpeg', help_text='MIME type (e.g., image/jpeg)', max_length=50)),
                ('image_size', models.PositiveIntegerField(blank=True, help_text='Image size in bytes', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='When the image was deleted', null=True)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='Admin who deleted the image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_lost_items', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
