# Generated by Django 5.2.1 on 2025-11-26 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0089_lostitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lostitem',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='lostitem',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='lostitem',
            name='image_data',
        ),
        migrations.RemoveField(
            model_name='lostitem',
            name='image_name',
        ),
        migrations.RemoveField(
            model_name='lostitem',
            name='image_size',
        ),
        migrations.RemoveField(
            model_name='lostitem',
            name='image_type',
        ),
    ]
