# Generated by Django 5.2.1 on 2025-11-26 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0090_remove_lostitem_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostitem',
            name='status',
            field=models.CharField(choices=[('lost', 'Lost'), ('found', 'Found')], default='lost', max_length=20),
        ),
    ]
