# Generated by Django 5.2.1 on 2025-12-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0091_alter_lostitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='condition',
            field=models.CharField(choices=[('In good condition', 'In good condition'), ('Needing repair', 'Needing repair'), ('Unserviceable', 'Unserviceable'), ('Obsolete', 'Obsolete'), ('No longer needed', 'No longer needed'), ('Not used since purchased', 'Not used since purchased'), ('Lost', 'Lost')], default='In good condition', max_length=100),
        ),
    ]
