# Generated by Django 5.2.1 on 2025-12-03 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0092_alter_property_condition'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('codename', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Admin Permission',
                'verbose_name_plural': 'Admin Permissions',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_limited_access',
            field=models.BooleanField(default=False, help_text='If True, this admin has limited access based on selected permissions. If False, admin has full access to all admin features.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='admin_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for admin users. Leave empty for full access (superuser-like) or select specific permissions for limited access.', related_name='users', to='app.adminpermission'),
        ),
    ]
