# Generated by Django 5.2.1 on 2025-12-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0094_supplyrequestbatch_approved_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrequestbatch',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('partially_approved', 'Partially Approved'), ('for_claiming', 'For Claiming'), ('active', 'Active'), ('returned', 'Returned'), ('overdue', 'Overdue'), ('expired', 'Expired'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('voided', 'Voided')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='borrowrequestitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('active', 'Active'), ('returned', 'Returned'), ('overdue', 'Overdue'), ('completed', 'Completed'), ('voided', 'Voided')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservationbatch',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('partially_approved', 'Partially Approved'), ('active', 'Active'), ('completed', 'Completed'), ('expired', 'Expired'), ('voided', 'Voided')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservationitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('active', 'Active'), ('completed', 'Completed'), ('expired', 'Expired'), ('voided', 'Voided')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='supplyrequestbatch',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('partially_approved', 'Partially Approved'), ('for_claiming', 'For Claiming'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('voided', 'Voided')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='supplyrequestitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('voided', 'Voided')], default='pending', max_length=20),
        ),
    ]
