# Generated by Django 5.2.1 on 2025-12-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0096_add_voided_by_to_supply_request_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplyrequestbatch',
            name='voided_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
