# Generated by Django 5.2.1 on 2025-12-12 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0098_add_voided_fields_to_reservation_and_borrow_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrequestitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('active', 'Active'), ('returned', 'Returned'), ('overdue', 'Overdue'), ('completed', 'Completed'), ('voided', 'Voided'), ('lost', 'Lost')], default='pending', max_length=20),
        ),
    ]
