# Generated by Django 5.2.1 on 2026-01-09 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0099_alter_borrowrequestitem_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PPMP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('file', models.FileField(upload_to='ppmp_files/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.department')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PPMP',
                'verbose_name_plural': 'PPMPs',
                'ordering': ['-year', '-upload_date'],
                'unique_together': {('department', 'year')},
            },
        ),
        migrations.CreateModel(
            name='PPMPItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(blank=True, max_length=255, null=True)),
                ('mode', models.CharField(blank=True, max_length=255, null=True)),
                ('supplies_materials_expense', models.CharField(blank=True, max_length=255, null=True)),
                ('office_supplies_expense', models.CharField(blank=True, max_length=255, null=True)),
                ('common_office_supplies', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('unit_measure', models.CharField(blank=True, max_length=100, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('row_number', models.PositiveIntegerField()),
                ('source_fund', models.CharField(blank=True, max_length=255, null=True)),
                ('ppmp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.ppmp')),
            ],
            options={
                'verbose_name': 'PPMP Item',
                'verbose_name_plural': 'PPMP Items',
                'ordering': ['ppmp', 'row_number'],
            },
        ),
    ]
