# Generated by Django 5.2.1 on 2026-01-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0100_ppmp_ppmpitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ppmpitem',
            name='common_office_supplies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ppmpitem',
            name='mode',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ppmpitem',
            name='office_supplies_expense',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ppmpitem',
            name='source_fund',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ppmpitem',
            name='supplies_materials_expense',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ppmpitem',
            name='unit',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ppmpitem',
            name='unit_measure',
            field=models.TextField(blank=True, null=True),
        ),
    ]
