# Generated by Django 5.2.1 on 2026-01-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0102_alter_ppmpitem_fields_to_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ppmpitem',
            name='source_fund',
        ),
        migrations.AddField(
            model_name='ppmpitem',
            name='total_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
