# Generated by Django 5.2.1 on 2026-01-09 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0103_remove_ppmpitem_source_fund_ppmpitem_total_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ppmpitem',
            name='total_quantity',
        ),
    ]
