# Generated by Django 5.2.1 on 2026-01-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0104_remove_ppmpitem_total_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='ppmpitem',
            name='released',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
