# Generated by Django 5.2.1 on 2026-01-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0105_ppmpitem_released'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='condition',
            field=models.CharField(choices=[('In good condition', 'In good condition'), ('Needing repair', 'Needing repair'), ('Unserviceable', 'Unserviceable'), ('Obsolete', 'Obsolete'), ('No longer needed', 'No longer needed'), ('Not used since purchased', 'Not used since purchased'), ('Lost', 'Lost'), ('For condemn', 'For condemn')], default='In good condition', max_length=100),
        ),
    ]
