# Generated by Django 5.2.1 on 2026-01-21 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0106_alter_property_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplyrequestitem',
            name='ppmp_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supply_requests', to='app.ppmpitem'),
        ),
        migrations.AddField(
            model_name='supplyrequestitem',
            name='ppmp_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
