# Generated by Django 5.2.1 on 2026-01-21 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0107_add_ppmp_tracking_to_supply_request_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyRequestPPMPAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_quantity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ppmp_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ppmpitem')),
                ('supply_request_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.supplyrequestitem')),
            ],
            options={
                'verbose_name': 'PPMP Allocation',
                'verbose_name_plural': 'PPMP Allocations',
                'unique_together': {('supply_request_item', 'ppmp_item')},
            },
        ),
        migrations.AddField(
            model_name='supplyrequestitem',
            name='ppmp_items',
            field=models.ManyToManyField(related_name='allocated_requests', through='app.SupplyRequestPPMPAllocation', to='app.ppmpitem'),
        ),
    ]
