# Generated by Django 5.2.1 on 2026-01-21 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0108_add_ppmp_multi_allocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplyrequestitem',
            name='ppmp_items',
        ),
        migrations.AddField(
            model_name='supplyrequestitem',
            name='ppmp_allocations',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='SupplyRequestPPMPAllocation',
        ),
    ]
