# Generated by Django 5.2.1 on 2026-02-03 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0109_add_ppmp_allocations_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='ppmp_item',
            field=models.ForeignKey(blank=True, help_text='Link to PPMP item for procurement tracking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='app.ppmpitem'),
        ),
    ]
