# Generated by Django 5.2.1 on 2026-02-03 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0110_add_ppmp_item_to_property'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='ppmp_item',
        ),
        migrations.AddField(
            model_name='property',
            name='ppmp_references',
            field=models.JSONField(blank=True, help_text='JSON field storing PPMP item references', null=True),
        ),
        migrations.CreateModel(
            name='PropertyPPMPAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_allocated', models.PositiveIntegerField(default=0)),
                ('allocated_date', models.DateTimeField(auto_now_add=True)),
                ('allocated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ppmp_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_allocations', to='app.ppmpitem')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ppmp_allocations', to='app.property')),
            ],
            options={
                'verbose_name': 'Property PPMP Allocation',
                'verbose_name_plural': 'Property PPMP Allocations',
                'ordering': ['-allocated_date'],
            },
        ),
    ]
