# Generated by Django 5.2.1 on 2026-02-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0111_remove_property_ppmp_item_property_ppmp_references_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='remarks',
            field=models.TextField(blank=True, help_text='Additional notes or comments about the property', null=True),
        ),
    ]
