# Generated by Django 5.2.1 on 2026-07-02 12:26

import django.db.models.deletion
from django.db import migrations, models


def forwards_copy_accountable_persons(apps, schema_editor):
    Property = apps.get_model('app', 'Property')
    AccountablePerson = apps.get_model('app', 'AccountablePerson')
    db_alias = schema_editor.connection.alias

    for prop in Property.objects.using(db_alias).all():
        raw_name = (prop.accountable_person or '').strip()
        if not raw_name:
            continue

        person, _ = AccountablePerson.objects.using(db_alias).get_or_create(name=raw_name)
        prop.accountable_person_ref_id = person.id
        prop.save(update_fields=['accountable_person_ref'])


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0115_slipsignatory'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountablePerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='property',
            name='accountable_person_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.accountableperson'),
        ),
        migrations.RunPython(forwards_copy_accountable_persons, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='property',
            name='accountable_person',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='accountable_person_ref',
            new_name='accountable_person',
        ),
    ]
