# Generated by Django 5.2.1 on 2026-07-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0116_accountableperson_alter_property_accountable_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountableperson',
            name='designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
