from django.urls import path
from . import views 
from django.contrib.auth.views import LogoutView
from .views import (
    DashboardPageView,
    UserBorrowRequestListView,
    UserSupplyRequestListView,
    UserDamageReportListView,
    UserReservationListView,
    ActivityPageView,
    SupplyListView,
    PropertyListView,
    CheckOutPageView,
    UserProfileListView,
    add_property,
    add_supply,
    edit_property,
    delete_property,
    edit_supply,
    delete_supply,
    create_user,
    request_detail,
    borrow_request_details,
    damage_report_detail,
    reservation_detail,
    mark_notification_as_read_ajax,
    mark_all_notifications_as_read,
    clear_all_notifications,
    logout_view,
    create_supply_request,
    create_borrow_request,
    approve_supply_request,
    approve_borrow_request,
    reject_supply_request,
    reject_borrow_request,
    get_supply_history,
    get_property_history,
    CustomLoginView,
    create_department,
    add_property_category,
    modify_property_quantity_generic,
    modify_supply_quantity_generic,
    AdminPasswordChangeView,
    AdminPasswordChangeDoneView,
    add_category,
    add_subcategory,
    get_subcategories,
    update_property_category,
    delete_property_category,
    export_supply_to_excel,
    export_property_to_excel,
    generate_sample_inventory_report,
)

urlpatterns = [
    path('', CustomLoginView.as_view(), name='login'),
    path('accounts/login/', CustomLoginView.as_view(), name='login'),

    path('logout/', logout_view, name='logout'),

    path('dashboard/', DashboardPageView.as_view(), name='dashboard'),
    path('activity/', ActivityPageView.as_view(), name='activity'),

    path('supplies/', SupplyListView.as_view(), name='supply_list'),
    path('add-supply/', add_supply, name='add_supply'),
    path('edit-supply/', edit_supply, name='edit_supply'),
    path('delete-supply/<int:pk>/', delete_supply, name='delete_supply'),

    path('property/', PropertyListView.as_view(), name='property_list'),
    path('add-property/', add_property, name='add_property'),
    path('edit-property/', edit_property, name='edit_property'),
    path('delete-property/<int:pk>/', delete_property, name='delete_property'),
    path('property/modify_quantity/', views.modify_property_quantity_generic, name='modify_property_quantity_generic'),
    path('add-property-category/', add_property_category, name='add_property_category'),
    path('update_property_category/', update_property_category, name='update_property_category'),
    path('delete_property_category/<int:category_id>/', delete_property_category, name='delete_property_category'),

    path('add-category/', add_category, name='add_category'),
    path('add-subcategory/', add_subcategory, name='add_subcategory'),
    path('get-subcategories/', get_subcategories, name='get_subcategories'),
    path('supply/modify_quantity/', views.modify_supply_quantity_generic, name='modify_supply_quantity_generic'),

    path('check-out/', CheckOutPageView.as_view(), name='checkout'),

    path('manage-users/', UserProfileListView.as_view(), name='manage_users'),
    path('create-user/', create_user, name='create_user'),
    path('create-department/', views.create_department, name='create_department'),
    path('edit-department/<int:dept_id>/', views.edit_department, name='edit_department'),
    path('delete-department/<int:dept_id>/', views.delete_department, name='delete_department'),

    path('my-borrow-requests/', UserBorrowRequestListView.as_view(), name='user_borrow_requests'),
    path('my-supply-requests/', UserSupplyRequestListView.as_view(), name='user_supply_requests'),
    path('my-damage-reports/', UserDamageReportListView.as_view(), name='user_damage_reports'),
    path('my-reservations/', UserReservationListView.as_view(), name='user_reservations'),

    path('create-supply-request/', create_supply_request, name='create_supply_request'),
    path('create-borrow-request/', create_borrow_request, name='create_borrow_request'),
    path('approve-supply-request/<int:request_id>/', approve_supply_request, name='approve_supply_request'),
    path('approve-borrow-request/<int:request_id>/', approve_borrow_request, name='approve_borrow_request'),
    path('reject-supply-request/<int:request_id>/', reject_supply_request, name='reject_supply_request'),
    path('reject-borrow-request/<int:request_id>/', reject_borrow_request, name='reject_borrow_request'),

    path('request/<int:pk>/', request_detail, name='request_detail'),
    path('borrow-request/<int:pk>/', borrow_request_details, name='borrow_request_details'),
    path('damage-report/<int:pk>/', damage_report_detail, name='damage_report_detail'),
    path('reservation/<int:pk>/', reservation_detail, name='reservation_detail'),

    path('mark-notification-read/', mark_notification_as_read_ajax, name='mark_notification_read'),
    path('mark-all-notifications-read/', mark_all_notifications_as_read, name='mark_all_notifications_read'),
    path('clear-all-notifications/', clear_all_notifications, name='clear_all_notifications'),

    path('api/supply/<int:supply_id>/history/', get_supply_history, name='supply_history'),
    path('api/property/<int:property_id>/history/', get_property_history, name='property_history'),

    path('get_supply_history/<int:supply_id>/', get_supply_history, name='get_supply_history'),
    path('get_property_history/<int:property_id>/', get_property_history, name='get_property_history'),
    path('change-password/', 
         AdminPasswordChangeView.as_view(), 
         name='password_change'),
    path('change-password/done/', 
         AdminPasswordChangeDoneView.as_view(), 
         name='password_change_done'),

    path('export-supply/', export_supply_to_excel, name='export_supply'),
    path('export-property/', export_property_to_excel, name='export_property'),
    path('sample-inventory-template/', generate_sample_inventory_report, name='sample_inventory_template'),
]
