from django.urls import path
from . import views 
from django.contrib.auth.views import LogoutView
from .views import (
    DashboardPageView,
    UserBorrowRequestBatchListView,
    UserSupplyRequestListView,
    UserDamageReportListView,
    UserReservationListView,
    ActivityPageView,
    SupplyListView,
    PropertyListView,
    CheckOutPageView,
    UserProfileListView,
    add_property,
    add_supply,
    edit_property,
    change_property_number,
    delete_property,
    edit_supply,
    delete_supply,
    report_bad_stock,
    bad_stock_list,
    borrow_batch_request_detail,
    claim_borrow_batch_items,
    return_borrow_batch_items,
    approve_borrow_item,
    reject_borrow_item,
    claim_individual_borrow_item,
    return_individual_borrow_item,
    create_user,
    request_detail,
    borrow_request_details,
    damage_report_detail,
    reservation_detail,
    reservation_batch_detail,
    approve_reservation_item,
    reject_reservation_item,
    approve_reservation_batch,
    reject_reservation_batch,
    mark_notification_as_read_ajax,
    mark_all_notifications_as_read,
    clear_all_notifications,
    logout_view,
    create_supply_request,
    add_to_list,
    remove_from_list,
    update_list_item,
    clear_supply_list,
    submit_list_request,
    create_borrow_request,
    approve_borrow_request,
    reject_borrow_request,
    get_supply_history,
    get_supply_quantity_activity,
    generate_quantity_activity_report,
    get_property_history,
    CustomLoginView,
    create_department,
    add_property_category,
    get_property_categories,
    modify_property_quantity_generic,
    modify_property_quantity_batch,
    modify_supply_quantity_generic,
    AdminPasswordChangeView,
    AdminPasswordChangeDoneView,
    add_category,
    add_subcategory,
    batch_request_detail,
    approve_batch_item,
    reject_batch_item,
    claim_batch_items,
    claim_individual_item,
    get_subcategories,
    update_property_category,
    delete_property_category,
    export_supply_to_excel,
    export_property_to_pdf_ics,
    export_inventory_count_form_cvsu,
    # generate_sample_inventory_report,
    get_supply_by_barcode,
    get_property_by_barcode,
    get_all_property_barcodes,
    get_all_supply_barcodes,
    archive_supply,
    unarchive_supply,
    download_requisition_slip,
    view_requisition_slip,
    archive_property,
    unarchive_property,
    ArchivedItemsView,
    update_supply_category,
    update_supply_subcategory,
    delete_supply_category,
    delete_supply_subcategory,
    get_top_requested_supplies,
    get_department_requests_filtered,
)

urlpatterns = [
    # Sample page for sidebar preview
    path('sample-admin/', views.sample_admin, name='sample_admin'),
    
    path('damaged-items/', views.DamagedItemsManagementView.as_view(), name='damaged_items_management'),
    path('update-damage-status/<int:pk>/', views.update_damage_status, name='update_damage_status'),
    path('update-property-condition/<str:property_number>/', views.update_property_condition, name='update_property_condition'),
    path('accounts/login/', CustomLoginView.as_view(), name='login'),

    path('logout/', logout_view, name='logout'),

    path('dashboard/', DashboardPageView.as_view(), name='dashboard'),
    path('api/near-expiry-count/', views.get_near_expiry_count, name='get_near_expiry_count'),
    path('api/pending-requests-count/', views.get_pending_requests_count, name='get_pending_requests_count'),
    path('activity/', ActivityPageView.as_view(), name='activity'),

    path('supplies/', SupplyListView.as_view(), name='supply_list'),
    path('add-supply/', add_supply, name='add_supply'),
    path('edit-supply/', edit_supply, name='edit_supply'),
    path('delete-supply/<int:pk>/', delete_supply, name='delete_supply'),
    path('report-bad-stock/', report_bad_stock, name='report_bad_stock'),
    path('bad-stock-list/', bad_stock_list, name='bad_stock_list'),

    path('property/', PropertyListView.as_view(), name='property_list'),
    path('add-property/', add_property, name='add_property'),
    path('edit-property/', edit_property, name='edit_property'),
    path('change-property-number/<int:pk>/', change_property_number, name='change_property_number'),
    path('delete-property/<int:pk>/', delete_property, name='delete_property'),
    path('property/<int:property_id>/mark-damaged/', views.admin_mark_property_damaged, name='admin_mark_property_damaged'),
    path('property/modify_quantity/', views.modify_property_quantity_generic, name='modify_property_quantity_generic'),
    path('property/modify_quantity_batch/', views.modify_property_quantity_batch, name='modify_property_quantity_batch'),
    path('add-property-category/', add_property_category, name='add_property_category'),
    path('get-property-categories/', get_property_categories, name='get_property_categories'),
    path('update_property_category/', update_property_category, name='update_property_category'),
    path('delete_property_category/<int:category_id>/', delete_property_category, name='delete_property_category'),

    path('add-category/', add_category, name='add_category'),
    path('add-subcategory/', add_subcategory, name='add_subcategory'),
    path('get-subcategories/', get_subcategories, name='get_subcategories'),
    path('supply/modify_quantity/', views.modify_supply_quantity_generic, name='modify_supply_quantity_generic'),
    path('update_supply_category/', views.update_supply_category, name='update_supply_category'),
    path('delete_supply_category/<int:category_id>/', delete_supply_category, name='delete_supply_category'),
    path('update_supply_subcategory/', views.update_supply_subcategory, name='update_supply_subcategory'),
    path('delete_supply_subcategory/<int:subcategory_id>/', delete_supply_subcategory, name='delete_supply_subcategory'),

    path('check-out/', CheckOutPageView.as_view(), name='checkout'),

    path('manage-users/', UserProfileListView.as_view(), name='manage_users'),
    path('create-user/', create_user, name='create_user'),
    path('create-department/', views.create_department, name='create_department'),
    path('edit-department/<int:dept_id>/', views.edit_department, name='edit_department'),
    path('delete-department/<int:dept_id>/', views.delete_department, name='delete_department'),

    path('my-borrow-requests/', UserBorrowRequestBatchListView.as_view(), name='user_borrow_requests'),
    path('my-supply-requests/', UserSupplyRequestListView.as_view(), name='user_supply_requests'),
    path('my-damage-reports/', UserDamageReportListView.as_view(), name='user_damage_reports'),
    path('my-reservations/', UserReservationListView.as_view(), name='user_reservations'),

    # Batch borrow request management URLs
    path('borrow-batch-detail/<int:batch_id>/', borrow_batch_request_detail, name='borrow_batch_request_detail'),
    path('claim-borrow-batch/<int:batch_id>/', claim_borrow_batch_items, name='claim_borrow_batch_items'),
    path('return-borrow-batch/<int:batch_id>/', return_borrow_batch_items, name='return_borrow_batch_items'),
    
    # Individual borrow item management URLs
    path('approve-borrow-item/<int:batch_id>/<int:item_id>/', approve_borrow_item, name='approve_borrow_item'),
    path('reject-borrow-item/<int:batch_id>/<int:item_id>/', reject_borrow_item, name='reject_borrow_item'),
    path('claim-borrow-item/<int:batch_id>/<int:item_id>/', claim_individual_borrow_item, name='claim_individual_borrow_item'),
    path('return-borrow-item/<int:batch_id>/<int:item_id>/', return_individual_borrow_item, name='return_individual_borrow_item'),

    path('create-supply-request/', create_supply_request, name='create_supply_request'),
    path('add-to-list/', add_to_list, name='add_to_list'),
    path('remove-from-list/', remove_from_list, name='remove_from_list'),
    path('update-list-item/', update_list_item, name='update_list_item'),
    path('clear-supply-list/', clear_supply_list, name='clear_supply_list'),
    path('submit-list-request/', submit_list_request, name='submit_list_request'),
    path('create-borrow-request/', create_borrow_request, name='create_borrow_request'),
    path('approve-borrow-request/<int:request_id>/', approve_borrow_request, name='approve_borrow_request'),
    path('reject-borrow-request/<int:request_id>/', reject_borrow_request, name='reject_borrow_request'),

    path('request/<int:pk>/', request_detail, name='request_detail'),
    path('borrow-request/<int:pk>/', borrow_request_details, name='borrow_request_details'),
    path('damage-report/<int:pk>/', damage_report_detail, name='damage_report_detail'),
    path('reservation/<int:pk>/', reservation_detail, name='reservation_detail'),
    path('reservation-batch/<int:batch_id>/', reservation_batch_detail, name='reservation_batch_detail'),
    path('reservation-batch/<int:batch_id>/approve/', approve_reservation_batch, name='approve_reservation_batch'),
    path('reservation-batch/<int:batch_id>/reject/', reject_reservation_batch, name='reject_reservation_batch'),
    path('reservation-batch/<int:batch_id>/item/<int:item_id>/approve/', approve_reservation_item, name='approve_reservation_item'),
    path('reservation-batch/<int:batch_id>/item/<int:item_id>/reject/', reject_reservation_item, name='reject_reservation_item'),

    path('mark-notification-read/', mark_notification_as_read_ajax, name='mark_notification_read'),
    path('mark-all-notifications-read/', mark_all_notifications_as_read, name='mark_all_notifications_read'),
    path('clear-all-notifications/', clear_all_notifications, name='clear_all_notifications'),
    path('get-latest-batch-request/', views.get_latest_batch_request, name='get_latest_batch_request'),
    path('get-latest-supply-request/', views.get_latest_supply_request, name='get_latest_supply_request'),
    path('get-latest-damage-report/', views.get_latest_damage_report, name='get_latest_damage_report'),
    path('get-latest-reservation/', views.get_latest_reservation, name='get_latest_reservation'),

    path('api/supply/<int:supply_id>/history/', get_supply_history, name='supply_history'),
    path('api/property/<int:property_id>/history/', get_property_history, name='property_history'),

    path('get_supply_history/<int:supply_id>/', get_supply_history, name='get_supply_history'),
    path('get_supply_quantity_activity/<int:supply_id>/', get_supply_quantity_activity, name='get_supply_quantity_activity'),
    path('generate_quantity_activity_report/', generate_quantity_activity_report, name='generate_quantity_activity_report'),
    path('get_property_history/<int:property_id>/', get_property_history, name='get_property_history'),
    path('change-password/', 
         AdminPasswordChangeView.as_view(), 
         name='password_change'),
    path('change-password/done/', 
         AdminPasswordChangeDoneView.as_view(), 
         name='password_change_done'),

    path('get_supply_by_barcode/<str:barcode>/', get_supply_by_barcode, name='get_supply_by_barcode'),
    path('get_property_by_barcode/<str:barcode>/', get_property_by_barcode, name='get_property_by_barcode'),
    path('get_all_property_barcodes/', get_all_property_barcodes, name='get_all_property_barcodes'),
    path('get_all_supply_barcodes/', get_all_supply_barcodes, name='get_all_supply_barcodes'),
    path('export-supply/', export_supply_to_excel, name='export_supply'),
    path('export-property-pdf-ics/', export_property_to_pdf_ics, name='export_property_pdf_ics'),
    path('export-inventory-count-form/', export_inventory_count_form_cvsu, name='export_inventory_count_form_cvsu'),
    # path('sample-inventory-template/', generate_sample_inventory_report, name='sample_inventory_template'),

    path('supply/<int:pk>/archive/', archive_supply, name='archive_supply'),
    path('supply/<int:pk>/unarchive/', unarchive_supply, name='unarchive_supply'),
    path('property/<int:pk>/archive/', archive_property, name='archive_property'),
    path('property/<int:pk>/unarchive/', unarchive_property, name='unarchive_property'),
    path('archived-items/', ArchivedItemsView.as_view(), name='archived_items'),
    
    # Batch request management URLs
    path('batch-request/<int:batch_id>/', batch_request_detail, name='batch_request_detail'),
    path('batch-request/<int:batch_id>/item/<int:item_id>/approve/', approve_batch_item, name='approve_batch_item'),
    path('batch-request/<int:batch_id>/item/<int:item_id>/reject/', reject_batch_item, name='reject_batch_item'),
    
    # Claiming workflow URLs
    path('batch-request/<int:batch_id>/claim/', claim_batch_items, name='claim_batch_items'),
    path('batch-request/<int:batch_id>/item/<int:item_id>/claim/', claim_individual_item, name='claim_individual_item'),
    
    # Requisition slip PDF URLs
    path('batch-request/<int:batch_id>/requisition-slip/download/', download_requisition_slip, name='download_requisition_slip'),
    path('batch-request/<int:batch_id>/requisition-slip/view/', view_requisition_slip, name='view_requisition_slip'),
    
    # Damage report image serving (from PostgreSQL database)
    path('damage-report/<int:report_id>/image/', views.damage_report_image, name='damage_report_image'),
    path('damage-report/<int:report_id>/delete-image/', views.delete_damage_report_image, name='delete_damage_report_image'),
    path('damage-reports/bulk-delete-images/', views.bulk_delete_damage_report_images, name='bulk_delete_damage_report_images'),
    
    # Admin Profile
    path('profile/', views.AdminProfileView.as_view(), name='admin_profile'),
    
    # Dashboard chart data API endpoints
    path('get-top-requested-supplies/', views.get_top_requested_supplies, name='get_top_requested_supplies'),
    path('get-department-requests-filtered/', views.get_department_requests_filtered, name='get_department_requests_filtered'),
]
